### ISSUE TITLE
Add Hoover H-Dry 300 HLE C10DCE-80 to integration? (API results from pyhon included here)

### ISSUE THREAD

**Issue by swampylee** [Andre0512/hon#10]
Hi, I don't have the skills to add this myself but thought this might be useful if someone was able to use the information from my Tumble Dryer to add to this integration.
```
User for hOn account: (redacted)
Password for hOn account:
========== TD - Garage Tumble ==========
data:
  active: False
  appliance:
    PK: user#eu-west-1(redacted)
    SK: app#(redacted)
    applianceId: (redacted)#2023-03-24T20:22:58Z
    applianceModelId: 774
    applianceStatus: 1
    applianceTypeId: 8
    applianceTypeName: TD
    attributes:
      acuVersion: 4.B.0
      chipset: ESP32D0WDQ5
      dictionaryId: 199
      lang: it-IT
      uiVersion: 3.C.5
    brand: hoover
    code: 31102475
    connectivity: wifi|ble
    coords:
      lat: (redacted)
      lng: (redacted)
    defaultWarrantyYears: 1
    eepromId: 739
    eepromName: 70008307
    enrollmentDate: 2023-03-24T20:22:58.531Z
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 3.2.5
    id: 774
    lastUpdate: 2023-03-24T20:23:08Z
    macAddress: (redacted)
    modelName: HLE C10DCE-80
    nickName: Garage Tumble
    purchaseDate: 2023-03-24T00:00:00.000Z
    sections:
      chatbot: True
      demo: True
      ecoDelayStart: True
      snap_wash: True
    serialNumber: (redacted)
    series: h-dry300
    structure: thermicCondensed
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/(redacted)
        - $aws/events/presence/connected/(redacted)
        - haier/things/(redacted)/event/appliancestatus/update
        - haier/things/(redacted)/event/discovery/update
  attributes:
    activity:
    commandHistory:
      command:
        ancillaryParameters:
          dryTimeMM: 70
          energyLabel: 0
          functionalId: 2
          programFamily: [dashboard|auto]
          programRules:
            dryLevel:
              opt3:
                1:
                  fixedValue: 1
                  typology: fixed
            dryTime:
            dryTimeMM:
                100:
                  fixedValue: 7
                  typology: fixed
                110:
                  fixedValue: 8
                  typology: fixed
                120:
                  fixedValue: 9
                  typology: fixed
                130:
                  fixedValue: 10
                  typology: fixed
                140:
                  fixedValue: 11
                  typology: fixed
                150:
                  fixedValue: 12
                  typology: fixed
                160:
                  fixedValue: 13
                  typology: fixed
                170:
                  fixedValue: 14
                  typology: fixed
                180:
                  fixedValue: 15
                  typology: fixed
                190:
                  fixedValue: 16
                  typology: fixed
                200:
                  fixedValue: 17
                  typology: fixed
                210:
                  fixedValue: 18
                  typology: fixed
                220:
                  fixedValue: 19
                  typology: fixed
                30:
                  fixedValue: 1
                  typology: fixed
                45:
                  fixedValue: 2
                  typology: fixed
                59:
                  fixedValue: 3
                  typology: fixed
                70:
                  fixedValue: 4
                  typology: fixed
                80:
                  fixedValue: 5
                  typology: fixed
                90:
                  fixedValue: 6
                  typology: fixed
            opt3:
              dryLevel:
                2|3|4:
                  fixedValue: 0
                  typology: fixed
          remoteActionable: 1
          remoteVisible: 1
          suggestedLoadD: 4
        applianceOptions:
          opt1: anticrease
          opt2: dryingManager
          opt3: bestIroning
          opt4: hybrid
        applianceType: TD
        attributes:
          channel: mobileApp
          origin: standardProgram
          prStr: Syntethics
        commandName: stopProgram
        device:
          appVersion: 1.53.7
          deviceModel: iPhone15,2
          mobileId: (redacted)
          mobileOs: ios
          osVersion: 16.3.1
        macAddress: (redacted)
        parameters:
          onOffStatus: 0
          programName: PROGRAMS.TD.SYNTHETICS
        timestamp: 2023-03-27T16:55:27.960Z
        transactionId: (redacted)_2023-03-27T16:55:27.960Z
    lastConnEvent:
      category: DISCONNECTED
      instantTime: 2023-04-01T15:23:01Z
      macAddress: (redacted)
      timestampEvent: 1680362581003
    parameters:
      anticrease: 1
      bestIroning: 0
      checkUpStatus: 0
      delayTime: 0
      doorStatus: 0
      dryCotton120: 0
      dryCotton180: 0
      dryCotton60: 0
      dryCottonBone: 0
      dryCottonHang: 0
      dryCottonIron: 0
      dryCottonMax: 0
      dryCottonStore: 4
      dryFilterStatus: 0
      dryLevel: 3
      dryLevelMgmt: 2
      drySynth120: 0
      drySynth180: 0
      drySynth60: 1
      drySynthBone: 0
      drySynthHang: 1
      drySynthIron: 0
      drySynthMax: 0
      drySynthStore: 0
      dryTime: 0
      dryingManager: 1
      errors: 00
      hybrid: 0
      machMode: 0
      opt5: 0
      opt6: 0
      opt7: 0
      opt8: 0
      prCode: 0
      prPhase: 0
      prPosition: 15
      program1: 0
      program10: 0
      program10t: 0
      program11: 0
      program11t: 0
      program12: 0
      program12t: 0
      program13: 0
      program13t: 0
      program14: 0
      program14t: 0
      program15: 4
      program15t: 121
      program16: 0
      program16t: 0
      program17: 0
      program17t: 0
      program18: 0
      program18t: 0
      program19: 0
      program19t: 0
      program1t: 0
      program2: 0
      program20: 0
      program20t: 0
      program21: 0
      program21t: 0
      program2t: 0
      program3: 0
      program3t: 0
      program4: 0
      program4t: 0
      program5: 0
      program5t: 0
      program6: 2
      program6t: 43
      program7: 0
      program7t: 0
      program8: 0
      program8t: 0
      program9: 0
      program9t: 0
      remainingTimeMM: 154
      remoteCtrValid: 0
      tumblingStatus: 0
      waterTankStatus: 0
    resultCode: 0
  pause: False
  pauseProgram:
    pause: 1
  resumeProgram:
    pause: 0
  startProgram:
    checkUpStatus: 1
    prStr: 0
    program: iot_checkup
  statistics:
    mostUsedPrograms:
      programsCounter: 6
      resultCode: 0
  stopProgram:
    onOffStatus: 0
settings:
  pauseProgram:
  resumeProgram:
  startProgram:
    program:
      - all_in_one
      - anti_odours
      - antiallergy
      - darks_and_coloured
      - delicates
      - eco
      - extra_hygiene
      - fresh_care
      - iot_checkup
      - iot_dry_anti_mites
      - iot_dry_baby
      - iot_dry_backpacks
      - iot_dry_bathrobe
      - iot_dry_bed_linen
      - iot_dry_bed_quilt
      - iot_dry_cotton
      - iot_dry_cuddly_toys
      - iot_dry_curtains
      - iot_dry_dehumidifier
      - iot_dry_delicate_tablecloths
      - iot_dry_delicates
      - iot_dry_denim_jeans
      - iot_dry_down_jacket
      - iot_dry_duvet
      - iot_dry_easy_iron_cotton
      - iot_dry_easy_iron_synthetics
      - iot_dry_gym_fit
      - iot_dry_lingerie
      - iot_dry_mixed
      - iot_dry_playsuits
      - iot_dry_rapid_30
      - iot_dry_rapid_59
      - iot_dry_regenerates_waterproof
      - iot_dry_shirts
      - iot_dry_small_load
      - iot_dry_swimsuits_and_bikinis
      - iot_dry_synthetics
      - iot_dry_tablecloths
      - iot_dry_technical_fabrics
      - iot_dry_warm_embrace
      - iot_dry_wool
      - jeans
      - mix_and_dry
      - rapid_30
      - rapid_45
      - rapid_59
      - relax_creases
      - shirts
      - small_load
      - synthetics
      - trainers
      - whites
      - woolmark
      - xxl_load
  stopProgram:
```
