### ISSUE TITLE
Add support for FHTW5620DNMG

### ISSUE THREAD

**Issue by choenig** [Andre0512/hon#126]
It would be nice if you could add support for the following device:

Essentially the "FreshZone" (Z3) is not supported, yet.

Thanks :)

```
========== REF - Kühlschrank ==========
data:
  additional_data:
    dictionaryId: 343
  appliance:
    PK: user#*****
    SK: app#xx-xx-xx-xx-xx-xx
    applianceId: xx-xx-xx-xx-xx-xx#2023-10-28T07:55:19Z
    applianceModelId: 10138
    applianceStatus: 1
    applianceTypeId: 14
    applianceTypeName: REF
    attributes:
      acuVersion: 0.0.0
      chipset: 1
      dictionaryId: 343
      eppParserSet: 1
      fwLabel: iotfw_epp
      idfVersion: 4.4.4
      kernelVersion: 10.4.3
      lang: it-IT
      uiVersion: 11.23.00
    brand: haier
    code: BB0V9HE0000
    connectivity: wifi|ble
    coords:
      lat: *****
      lng: *****
    defaultWarrantyYears: 2
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 2023-10-28T07:55:19.209Z
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 5.15.0
    id: 10138
    lastUpdate: 2023-10-28T07:57:01Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: HTW5620DNMG
    nickName: Kühlschrank
    purchaseDate: 2023-10-23T22:00:00.000Z
    sections:
      inside_view: True
    serialNumber: BB*****1
    series: romania
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
  attributes:
    activity:
    commandHistory:
      command:
        ancillaryParameters:
          nameVariants: series
          programFamily: [dashboard]
          remoteActionable: 1
          remoteVisible: 1
          zone: fridge_freezer
        applianceOptions:
        applianceType: REF
        attributes:
          channel: mobileApp
          energyLabel: 0
          origin: standardProgram
        commandName: startProgram
        device:
          appVersion: 2.1.2
          deviceModel: exynos9820
          mobileId: f*****b
          mobileOs: android
          osVersion: 31
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          intelligenceMode: 1
        timestamp: 2023-10-28T16:25:26.223Z
        transactionId: xx-xx-xx-xx-xx-xx_2023-10-28T16:25:26.223Z
      timestampAccepted: 2023-10-30T20:50:29.6Z
      timestampExecuted: 2023-10-30T20:50:30.4Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 2023-11-04T07:32:22Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1699083142722
    modeZ1: no_mode
    modeZ2: no_mode
    parameters:
      debugEnabled: 0
      doorStatusZ1: 0
      errors: 00
      highTransRate: 1
      holidayMode: 0
      humidityEnv: 0
      intelligenceMode: 1
      quickModeZ1: 0
      quickModeZ2: 0
      statusSyncRate: 1440
      stdTransRate: 3600
      tempEnv: 21
      tempSelZ1: 6
      tempSelZ2: -18
      tempSelZ3: 2
      transMode: 0
    programName: No Program
    resultCode: 0
  settings:
    custom:
      category: setParameters
    parameters:
      tempSelZ1: 6
      tempSelZ2: -18
      tempSelZ3: 2
  startProgram:
    ancillaryParameters:
      nameVariants: series
      programFamily: [dashboard]
      remoteActionable: 1
      remoteVisible: 1
      zone: [fridge|freezer]
    custom:
      program: auto_set
    parameters:
      intelligenceMode: 1
  statistics:
    mostUsedPrograms:
    mostUsedRecipes:
    programsCounter: 0
  stopProgram:
    parameters:
      holidayMode: 0
      intelligenceMode: 0
      quickModeZ1: 0
      quickModeZ2: 0
commands:
  settings:
    category:
      - setConfig
      - setParameters
    tempSelZ1:
      max: 8
      min: 2
      step: 1
    tempSelZ2:
      max: -16
      min: -24
      step: 1
    tempSelZ3:
      max: 5
      min: 0
      step: 1
  startProgram:
    program:
      - auto_set
      - holiday
      - super_cool
      - super_freeze
    programFamily:
      - dashboard
    zone:
      - fridge
      - freezer
      - fridge_freezer
```
