### ISSUE TITLE
Automation trickery

### ISSUE THREAD

**Issue by ArMaTeC** [Andre0512/hon#128]
Hi all,

I hope someone can assist on this issue im having i can get any of the live triggers to work that are listed below the only one that has ever triggered was the Washing-started but this happens after a wash is finished and I turn off the appliance 

```

- id: Washing-finished
  alias: Washing finished
  trigger:
    - platform: state
      entity_id: sensor.hdd4106ambcb_80_machine_status
      from: "running"
      to: "ended"
  action:
    - service: chime_tts.say
      data:
        chime_path: custom_components/chime_tts/mp3s/mario_coin.mp3
        delay: 450
        final_delay: 0
        tts_playback_speed: 100
        volume_level: 1
        message: Washer finished
        tts_platform: tts.piper
        join_players: true
        unjoin_players: true
        gender: female
      target:
        entity_id:
          - media_player.karl_bedroom_speaker
          - media_player.living_room_speaker
          - media_player.office_room_speaker
  mode: single

- id: Washing-error
  alias: Washing error
  trigger:
    - platform: state
      entity_id: sensor.hdd4106ambcb_80_machine_status
      from: 
        - "running"
        - "ready"
        - "pause"
        - "scheduled"
        - "test"
        - "ending"
      to: "error"
  action:
    - service: chime_tts.say
      data:
        chime_path: custom_components/chime_tts/mp3s/dun_dun_dun.mp3
        delay: 450
        final_delay: 0
        tts_playback_speed: 100
        volume_level: 1
        message: Washer error
        tts_platform: tts.piper
        join_players: true
        unjoin_players: true
        gender: female
      target:
        entity_id:
          - media_player.karl_bedroom_speaker
          - media_player.living_room_speaker
          - media_player.office_room_speaker
  mode: single

- id: Washing-started
  alias: Washing started
  trigger:
    - platform: state
      entity_id: sensor.hdd4106ambcb_80_machine_status
      to: "ready"
      from: "running"
  action:
    - service: chime_tts.say
      data:
        chime_path: custom_components/chime_tts/mp3s/mario_coin.mp3
        delay: 450
        final_delay: 0
        tts_playback_speed: 100
        volume_level: 1
        message: Washer Started
        tts_platform: tts.piper
        join_players: true
        unjoin_players: true
        gender: female
      target:
        entity_id:
          - media_player.karl_bedroom_speaker
          - media_player.living_room_speaker
          - media_player.office_room_speaker
  mode: single


- id: Washing-paused
  alias: Washing paused
  trigger:
    - platform: state
      entity_id: sensor.hdd4106ambcb_80_machine_status
      to: "ready"
      from: "pause"
  action:
    - service: chime_tts.say
      data:
        chime_path: custom_components/chime_tts/mp3s/mario_coin.mp3
        delay: 450
        final_delay: 0
        tts_playback_speed: 100
        volume_level: 1
        message: Washer Pause
        tts_platform: tts.piper
        join_players: true
        unjoin_players: true
        gender: female
      target:
        entity_id:
          - media_player.karl_bedroom_speaker
          - media_player.living_room_speaker
          - media_player.office_room_speaker
  mode: single
```
