### ISSUE TITLE
Haier Tumble Dryer: HD90-A35XLINE-DE

### ISSUE THREAD

**Issue by tbrtje** [Andre0512/hon#132]
This Dryer seems to be the same as the HD90-A3TEAM5 and the HD90-A3959.

It does not display when adding the integration to home assistant though.

Here is the attributes and commands output for pyhon if that helps:

```
  attributes:
    active: True
    activity:
      activityExecutionStarted: 2023-11-25 11:20:45
      activityStarted: 2023-11-25T11:20:45Z
      applianceTypeName: TD
      attributes:
        antiCreaseTime: 0
        channel: appliance
        delayTime: 0
        dryLevel: 14
        dryTimeMM: 270
        origin: dashboard
        prCode: 64
        programCluster: traditional
        programFamily: [dashboard|auto]
        programName: HQD_MIX
        remainingTimeMM: 180
        remoteCtrValid: 0
        sterilizationStatus: 0
      category: CYCLE
      macAddress: 94-b5-55-e8-66-c4
      resultCode: 0
      ttl: 1708687245
    lastConnEvent:
      category: CONNECTED
      instantTime: 2023-11-25T12:14:17Z
      macAddress: 94-b5-55-e8-66-c4
      timestampEvent: 1700914457323
    parameters:
      airWashMode: 1
      airwashSprayTime: 0
      anionStatus: 0
      antiCreaseTime: 0
      buzzerDisabled: 1
      cloudProgId: 0
      cloudProgSrc: 1
      debugEnabled: 0
      delayTime: 0
      delicateStatus: 0
      doorStatus: 0
      dryLevel: 14
      dryMode: 1
      dryTimeMM: 144
      errors: 00
      fastDryStatus: 0
      forceDelete: 0
      highTransRate: 1
      ironRemindStatus: 0
      ironingStatus: 0
      lockStatus: 0
      machMode: 2
      message: 0
      mitesRemovalStatus: 0
      onOffStatus: 1
      pause: 0
      prCode: 64
      prPhase: 15
      programClass: 1
      remainingStandbyTime: 2
      remainingTimeMM: 11
      remoteCtrValid: 0
      statusSyncRate: 1440
      stdTransRate: 1
      sterilizationStatus: 0
      tempLevel: 4
      texture: 0
      transMode: 0
    pause: False
    programName: No Program
    resultCode: 0
  pauseProgram:
    parameters:
      pause: 1
  resumeProgram:
    parameters:
      pause: 0
  settings:
    custom:
      category: setConfig
    parameters:
      httpEndpoint: 0
      mqttEndpoint: 0
  startProgram:
    ancillaryParameters:
      energyLabel: 2
      prPosition: 8
      programCluster: specialCare
      programFamily: [guided|auto]
      programType: D
      remoteActionable: 1
      remoteVisible: 0
      suggestedLoadD: 4.5
      tumblingStatus: 0
    custom:
      program: iot_dry_baby
    parameters:
      airWashMode: 1
      airwashSprayTime: 0
      anionStatus: 0
      antiCreaseTime: 0
      buzzerDisabled: 1
      cloudProgId: 0
      cloudProgSrc: 2
      delayTime: 0
      delicateStatus: 0
      dryLevel: 14
      dryMode: 1
      dryTimeMM: 0
      fastDryStatus: 0
      ironRemindStatus: 1
      lockStatus: 0
      mitesRemovalStatus: 0
      onOffStatus: 1
      operationName: grDryCloudProg
      pause: 0
      prCode: 69
      programClass: 1
      sterilizationStatus: 0
      tempLevel: 4
      texture: 47
  statistics:
    drumCleaning:
      count: 0
      percentage: 0
      remaining: 100
      tot: 100
    filterCleaning:
      count: 0
      percentage: 0
      remaining: 15
      tot: 15
    lastCheckup: None
    mostUsedPrograms:
    programsCounter: 0
    resultCode: 0
    sprayArmsCleaning: 0
  stopProgram:
    parameters:
      returnStandby: 1
commands:
  settings:
    category:
      - setConfig
  startProgram:
    antiCreaseTime:
      max: 360
      min: 0
      step: 360
    delayTime:
      max: 1410
      min: 0
      step: 30
    dryLevel:
      max: 14
      min: 12
      step: 1
    dryTimeMM:
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
    energyLabel:
      max: 5
      min: 1
      step: 1
    program:
      - hqd_baby_care
      - hqd_bath_towel
      - hqd_bed_sheets
      - hqd_bulky
      - hqd_casual
      - hqd_cold_wind_timing
      - hqd_cotton
      - hqd_curtain
      - hqd_delicate
      - hqd_duvet
      - hqd_feather
      - hqd_hot_wind_timing
      - hqd_hygienic
      - hqd_i_refresh
      - hqd_i_refresh_pro
      - hqd_jacket
      - hqd_jeans
      - hqd_mix
      - hqd_night_dry
      - hqd_outdoor
      - hqd_precious_cure
      - hqd_quick_30
      - hqd_quick_dry
      - hqd_quilt
      - hqd_refresh
      - hqd_shirt
      - hqd_shoes
      - hqd_silk
      - hqd_sports
      - hqd_synthetics
      - hqd_timer
      - hqd_underwear
      - hqd_wool
      - hqd_working_suit
      - iot_dry_baby
      - iot_dry_backpacks
      - iot_dry_bathrobe
      - iot_dry_bed_linen
      - iot_dry_cotton
      - iot_dry_cuddly_toys
      - iot_dry_curtains
      - iot_dry_delicates
      - iot_dry_denim_jeans
      - iot_dry_down_jacket
      - iot_dry_duvet
      - iot_dry_gym_fit
      - iot_dry_lingerie
      - iot_dry_mixed
      - iot_dry_pet_accessories
      - iot_dry_pet_hair_removal
      - iot_dry_rapid_30
      - iot_dry_rapid_59
      - iot_dry_shirts
      - iot_dry_swimsuits_and_bikinis
      - iot_dry_synthetics
      - iot_dry_tablecloths
      - iot_dry_technical_fabrics
      - iot_dry_wool
    programFamily:
      - wmsync
      - guided
      - voice
      - care
      - auto
      - wmsync_guided_voice_care_auto
    sterilizationStatus:
      max: 1
      min: 0
      step: 1
    tempLevel:
      max: 4
      min: 1
      step: 1
    tumblingStatus:
      max: 1
      min: 0
      step: 1
```
