### ISSUE TITLE
New washing machine HW70-B14959TU1

### ISSUE THREAD

**Issue by tomhanak** [Andre0512/hon#176]
On the label is HW70-B14959TU1-S as well as in Home Assistent. But in extended waranty form it complained that its serial number does not belong to that model and it has been accepted for HW70-B14959TU1 model.

<details>
<summary>Device Info</summary>

```
data:
  additional_data:
    dictionaryId: 150
    options: haier_SoakPrewashSelection
  appliance:
    PK: user#eu-west-1:c0f806c3-fad2-cb1c-60d0-0607043649d0
    SK: app#xx-xx-xx-xx-xx-xx
    applianceId: xx-xx-xx-xx-xx-xx#1970-01-01T00:00:00.0Z
    applianceModelId: 13284
    applianceStatus: 1
    applianceTypeId: 1
    applianceTypeName: WM
    attributes:
      acuVersion: 0.0.0
      chipset: 1
      dictionaryId: 150
      eppParserSet: 1
      fwLabel: iotfw_epp
      idfVersion: 4.4.4
      kernelVersion: 10.4.3
      lang: it-IT
      uiVersion: 23.05.15
    brand: haier
    code: CEAAFHE0100
    connectivity: wifi|ble
    defaultWarrantyYears: 2
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 1970-01-01T00:00:00.0Z
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 5.15.0
    id: 13284
    lastUpdate: 1970-01-01T00:00:00.0Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: HW70-B14959TU1-S
    purchaseDate: 1970-01-01T00:00:00.0Z
    sections:
      chatbot: True
      demo: True
      double_pairing_hidden: True
      ecoDelayStart: True
      snap_wash: True
    series: 959
    sfPersonAccountId: 001R200000BduC8IAJ
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
  attributes:
    active: True
    activity:
      activityExecutionStarted: 2024-02-29 15:35:19
      activityStarted: 1970-01-01T00:00:00.0Z
      applianceTypeName: WM
      attributes:
        antiWrinkle: 1
        appVersion: 2.6.5
        autoDetergentStatus: 0
        autoSoftenerStatus: 0
        channel: mobileApp
        delayStatus: 0
        delayTime: 0
        deviceModel: RM6785
        dirtyLevel: 0
        dryLevel: 0
        dryProgFlag: 0
        dryTime: 0
        energyLabel: 5
        haier_SoakPrewashSelection: 0
        liquidDetergentDose: 3
        mainWashTime: 5
        mobileOs: android
        nightWashStatus: 0
        origin: standardProgram
        osVersion: 33
        permanentPressStatus: 0
        powderDetergentDose: 3
        prCode: 89
        prPosition: 17
        prStrDisp: Sportovní 25'
        principalUserId: 001R200000BduC8IAJ
        programCluster: sport
        programFamily: [hidden|dashboard]
        programIntensity: standard
        programName: HQD_SPORT
        programType: W
        remainingTimeMM: 26
        remoteCtrValid: 1
        rinseIterationTime: 4
        rinseIterations: 1
        spinSpeed: 800
        suggestedLoadW: 3.5
        temp: 20
      category: CYCLE
      macAddress: xx-xx-xx-xx-xx-xx
      resultCode: 0
      ttl: 1716996919
    commandHistory:
      command:
        ancillaryParameters:
          antiWrinkle: 1
          energyLabel: 5
          liquidDetergentDose: 3
          powderDetergentDose: 3
          prPosition: 17
          programCluster: sport
          programFamily: [hidden|dashboard]
          programIntensity: standard
          programType: W
          remoteActionable: 1
          remoteVisible: 1
          suggestedLoadW: 3.5
          tempContribution: 1
        applianceOptions:
          haier_SoakPrewashSelection: haier_SoakPrewashSelection
        applianceType: WM
        attributes:
          channel: mobileApp
          energyLabel: 5
          origin: standardProgram
          prStr: Sportovní 25'
        commandName: startProgram
        device:
          appVersion: 2.6.5
          deviceModel: RM6785
          mobileId: d0e225678ef62b68
          mobileOs: android
          osVersion: 33
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          antiAllergyStatus: 0
          autoDetergentStatus: 0
          autoDisinfectantStatus: 0
          autoSoftenerStatus: 0
          cloudProgId: 255
          cloudProgSrc: 2
          creaseResistSoakStatus: 0
          delayStatus: 0
          delayTime: 0
          detergentBStatus: 0
          dryProgFlag: 0
          dryTime: 0
          energySavingStatus: 0
          haier_ConstantTempStatus: 1
          haier_MainWashRotateTime: 20
          haier_MainWashSpeed: 45
          haier_MainWashStopTime: 5
          haier_MainWashWaterLevel: 3
          haier_RinseRotateTime: 15
          haier_RinseSpeed: 45
          haier_RinseStopTime: 10
          haier_SoakPrewashRotateTime: 15
          haier_SoakPrewashSelection: 0
          haier_SoakPrewashSpeed: 45
          haier_SoakPrewashStopTime: 10
          haier_SoakPrewashTemperature: 30
          haier_SoakPrewashTime: 15
          highWaterLevelStatus: 0
          intelligenceStatus: 0
          ironRemindStatus: 0
          lockStatus: 0
          mainWashTime: 5
          nightWashStatus: 0
          operationName: grOnlineWash
          permanentPressStatus: 0
          prCode: 89
          rinseIterationTime: 4
          rinseIterations: 1
          soakWashStatus: 0
          speedUpStatus: 0
          spinSpeed: 800
          strongStatus: 0
          temp: 20
          texture: 1
          uvSterilizationStatus: 0
          voiceStatus: 0
          washerDryIntensity: 1
          weight: 2
        programName: PROGRAMS.WM_WD.HQD_SPORT
        timestamp: 1970-01-01T00:00:00.0Z
        transactionId: xx-xx-xx-xx-xx-xx_1970-01-01T00:00:00.0Z
      timestampAccepted: 1970-01-01T00:00:00.0Z
      timestampExecuted: 1970-01-01T00:00:00.0Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 1970-01-01T00:00:00.0Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1709220950892
    parameters:
      actualWeight: 2
      airWashTempLevel: 0
      airWashTime: 0
      antiAllergyStatus: 0
      autoDetergentStatus: 0
      autoDisinfectantStatus: 0
      autoSoftenerStatus: 0
      buzzerDisabled: 1
      buzzerDisabledCurrent: 0
      clothesAnionStatus: 0
      cloudProgId: 255
      cloudProgSrc: 2
      creaseResistSoakStatus: 0
      currentElectricityUsed: 0.14
      currentWashCycle: 1
      currentWaterUsed: 23
      debugEnabled: 0
      defSetAllowed: 0
      delayStatus: 0
      detWarn: 0
      detergentBStatus: 0
      detergentPercent: 0
      detergentType: 1
      dirtyLevel: 0
      doorLockStatus: 1
      doorStatus: 0
      dryCleaningNeeded: 0
      dryLevel: 0
      dryProgFlag: 0
      dryStatus: 0
      dryTime: 0
      energySavingStatus: 0
      errors: 00
      forceDelete: 0
      haier_DetergentWeight: 0
      haier_SoftenerWeight: 0
      highTransRate: 1
      highWaterLevelStatus: 0
      intelligenceStatus: 0
      laundryCycleStatus: 1
      lockStatus: 0
      loosenStatus: 0
      machMode: 2
      message: 0
      nightWashStatus: 0
      pause: 0
      permanentPressStatus: 0
      prCode: 89
      prPhase: 11
      program1: 0
      program10: 0
      program11: 0
      program12: 0
      program13: 0
      program14: 0
      program15: 0
      program16: 0
      program17: 0
      program18: 0
      program19: 0
      program2: 1
      program20: 0
      program21: 0
      program22: 0
      program23: 0
      program24: 0
      program25: 0
      program3: 0
      program4: 0
      program5: 0
      program6: 0
      program7: 0
      program8: 0
      program9: 0
      programStats: ;1
      purifiedWashStatus: 0
      remainingMainWashTime: 0
      remainingRinseIterations: 0
      remainingStandbyTime: 1417
      remainingTimeMM: 5
      remoteCtrValid: 1
      shoesAnionStatus: 0
      soakWashStatus: 0
      softWarn: 0
      speedUpStatus: 0
      spinSpeed: 800
      stainType: 0
      standbyTimeExtended: 1
      statusSyncRate: 1440
      stdTransRate: 1
      steamStatus: 0
      strongStatus: 0
      temp: 20
      temp0to30: 1
      temp40: 0
      temp60to90: 0
      testCmdReceiveStatus: 0
      texture: 1
      totalElectricityUsed: 0.19
      totalWashCycle: 1
      totalWaterUsed: 47
      transMode: 0
      uvSterilizationStatus: 0
      voiceModuleDataDef: 130
      voiceModuleOnOffStatus: 1
      voiceModuleVolume: 0
      voiceModuleWakeStatus: 0
      voiceModuleWakeUp: 0
      voiceStatus: 0
      washSpeed: 0
      washerDryIntensity: 1
      weight: 2
    pause: False
    programName: No Program
    resultCode: 0
  pauseProgram:
    parameters:
      pause: 1
  resumeProgram:
    parameters:
      pause: 0
  settings:
    custom:
      category: setConfig
    parameters:
      httpEndpoint: 0
      mqttEndpoint: 0
  startProgram:
    ancillaryParameters:
      antiWrinkle: 1
      energyLabel: 4
      liquidDetergentDose: 4
      powderDetergentDose: 4
      prPosition: 1
      programCluster: traditional
      programFamily: [dashboard|smart]
      programIntensity: standard
      programType: W
      remoteActionable: 1
      remoteVisible: 1
      suggestedLoadW: 7
      tempContribution: 1
    custom:
      program: hqd_smart
    parameters:
      antiAllergyStatus: 0
      autoDetergentStatus: 0
      autoDisinfectantStatus: 0
      autoSoftenerStatus: 0
      cloudProgId: 255
      cloudProgSrc: 2
      creaseResistSoakStatus: 0
      delayStatus: 0
      delayTime: 0
      detergentBStatus: 0
      dryLevel: 0
      dryProgFlag: 0
      dryTime: 0
      energySavingStatus: 0
      haier_ConstantTempStatus: 1
      haier_MainWashRotateTime: 20
      haier_MainWashSpeed: 45
      haier_MainWashStopTime: 5
      haier_MainWashWaterLevel: 3
      haier_RinseRotateTime: 15
      haier_RinseSpeed: 45
      haier_RinseStopTime: 10
      haier_SoakPrewashRotateTime: 15
      haier_SoakPrewashSelection: 0
      haier_SoakPrewashSpeed: 45
      haier_SoakPrewashStopTime: 10
      haier_SoakPrewashTemperature: 30
      haier_SoakPrewashTime: 15
      highWaterLevelStatus: 0
      intelligenceStatus: 0
      lockStatus: 0
      mainWashTime: 5
      nightWashStatus: 0
      operationName: grOnlineWash
      permanentPressStatus: 0
      prCode: 89
      rinseIterationTime: 4
      rinseIterations: 1
      soakWashStatus: 0
      speedUpStatus: 0
      spinSpeed: 800
      strongStatus: 0
      temp: 20
      texture: 1
      uvSterilizationStatus: 0
      voiceStatus: 0
      washerDryIntensity: 1
      weight: 2
    remainingTimes:
      remainingTime: 68
  statistics:
    drawerCleaning:
      count: 1
      percentage: 1
      remaining: 99
      tot: 100
    drumCleaning:
      count: 1
      percentage: 1
      remaining: 99
      tot: 100
    filterCleaning:
      count: 1
      percentage: 1
      remaining: 99
      tot: 100
    lastCheckup: None
    loadingPercentage:
    mostUsedPrograms:
    programsCounter: 1
    resultCode: 0
    temperatureUsage:
      temp0to30: 1
      temp40: 0
      temp60to90: 0
  stopProgram:
    parameters:
      onOffStatus: 0
commands:
  settings:
    category:
      - setConfig
  startProgram:
    delayStatus:
      max: 1
      min: 0
      step: 1
    delayTime:
      max: 1410
      min: 0
      step: 30
    energyLabel:
      max: 5
      min: 3
      step: 1
    haier_SoakPrewashSelection:
      max: 2
      min: 0
      step: 2
    mainWashTime:
      max: 120
      min: 5
      step: 5
    nightWashStatus:
      max: 1
      min: 0
      step: 1
    permanentPressStatus:
      max: 1
      min: 0
      step: 1
    program:
      - Rychlý 15'
      - hqd_20_degrees
      - hqd_allergy
      - hqd_autoclean
      - hqd_babycare
      - hqd_checkup
      - hqd_cottons
      - hqd_delicate_cradle
      - hqd_duvet
      - hqd_eco_40_60_degrees
      - hqd_handwash_wool
      - hqd_mix
      - hqd_quick_15
      - hqd_quick_wash_57
      - hqd_refresh
      - hqd_rinse
      - hqd_shirts
      - hqd_smart
      - hqd_spin
      - hqd_sport
      - hqd_synthetic_and_coloured
      - iot_wash_anti_mites
      - iot_wash_ariel_clean_cycle
      - iot_wash_ariel_cold_cycle
      - iot_wash_ariel_fresh_cycle
      - iot_wash_baby_sanitizer
      - iot_wash_backpacks
      - iot_wash_bathrobe
      - iot_wash_bed_linen
      - iot_wash_bleaching
      - iot_wash_blood_stains
      - iot_wash_cashmere
      - iot_wash_chocolate_stains
      - iot_wash_cold_wash
      - iot_wash_colored
      - iot_wash_colored_anti_stain
      - iot_wash_colored_delicate
      - iot_wash_coloured
      - iot_wash_cotton
      - iot_wash_cuddly_toys
      - iot_wash_curtains
      - iot_wash_dark
      - iot_wash_delicate
      - iot_wash_delicate_antiallergy
      - iot_wash_delicate_colors
      - iot_wash_delicate_dark
      - iot_wash_delicate_tablecloths
      - iot_wash_delicate_whites
      - iot_wash_denim_jeans
      - iot_wash_diving_suits
      - iot_wash_down_jackets
      - iot_wash_fruit_stains
      - iot_wash_handwash
      - iot_wash_handwash_colored
      - iot_wash_handwash_dark
      - iot_wash_lingerie
      - iot_wash_masks_refresh
      - iot_wash_masks_sanification
      - iot_wash_mats
      - iot_wash_men_s_trousers
      - iot_wash_mixed
      - iot_wash_new_clothes
      - iot_wash_perfect_white
      - iot_wash_pets
      - iot_wash_pets_hair_removal
      - iot_wash_pets_odours_stains_removal
      - iot_wash_rapid_14
      - iot_wash_rapid_30
      - iot_wash_rapid_44
      - iot_wash_rapid_59
      - iot_wash_resistant_colored
      - iot_wash_resistant_dark
      - iot_wash_resistant_whites
      - iot_wash_rinse
      - iot_wash_silk
      - iot_wash_ski_suit
      - iot_wash_spin
      - iot_wash_sport
      - iot_wash_sport_anti_odor
      - iot_wash_swimsuits_and_bikinis
      - iot_wash_synthetic
      - iot_wash_tablecloths
      - iot_wash_technical_fabrics
      - iot_wash_technical_jackets
      - iot_wash_trainers
      - iot_wash_whites
      - iot_wash_wine_stains
      - iot_wash_wool
    programCluster:
      - traditional
      - eco
      - traditional_eco
    programFamily:
      - hidden
      - guided
      - dashboard
      - hidden_guided_dashboard
    rinseIterations:
      max: 5
      min: 0
      step: 1
    spinSpeed:
      - 0
      - 400
      - 600
      - 800
      - 1000
      - 1200
      - 1400
    temp:
      - 0
      - 20
      - 30
      - 40
      - 60
      - 90
versions:
  hon: 0.13.0
  pyhOn: 0.16.0

```
</details>

**Data Archive**
[wm_13284.zip](https://github.com/Andre0512/hon/files/14450671/wm_13284.zip)
