### ISSUE TITLE
Add Freezer: HAIER H3F330WDH1 

### ISSUE THREAD

**Issue by Joeri-Belgium** [Andre0512/hon#177]
**Is your feature request related to a problem? Please describe.**
My Freezer seems not to be in it.

**Describe the solution you'd like**
Add my freezer. Temp and events would be great.

**Device Log**
Post your device info here (if available)

```
data:
  additional_data:
    dictionaryId: 265
  appliance:
    PK: user#eu-west-1:c0f806c3-faa6-cb6f-23ea-495b6244f1fe
    SK: app#xx-xx-xx-xx-xx-xx
    applianceId: xx-xx-xx-xx-xx-xx#1970-01-01T00:00:00.0Z
    applianceModelId: 10131
    applianceStatus: 1
    applianceTypeId: 16
    applianceTypeName: FRE
    attributes:
      acuVersion: 0.0.0
      chipset: 1
      dictionaryId: 265
      eppParserSet: 1
      fwLabel: iotfw_epp
      idfVersion: 4.4.4
      kernelVersion: 10.4.3
      lang: it-IT
      uiVersion: 12.04.00
    brand: haier
    code: B30KK7E0000
    connectivity: wifi|ble
    defaultWarrantyYears: 2
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 1970-01-01T00:00:00.0Z
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 5.15.0
    id: 10131
    lastUpdate: 1970-01-01T00:00:00.0Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: H3F330WDH1
    nickName: Vriezer
    purchaseDate: 1970-01-01T00:00:00.0Z
    sections:
      chatbot: True
      double_pairing_hidden: True
      inside_view: True
      my_profile_temperature: True
      proactive_temperature: True
      smart_check_up: True
      visual_tricks: True
    series: instaswitch
    seriesVersion: up60Series7
    sfPersonAccountId: 001R200000CGkw4IAD
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
  attributes:
    activity:
    lastConnEvent:
      category: CONNECTED
      instantTime: 1970-01-01T00:00:00.0Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1709294386319
    parameters:
      debugEnabled: 0
      doorStatusZ2: 0
      errors: 00
      highTransRate: 1
      quickModeZ1: 0
      quickModeZ2: 0
      showStatus: 0
      statusSyncRate: 1440
      stdTransRate: 3600
      tempEnv: 21
      tempSelZ3: -18
      transMode: 0
    resultCode: 0
  settings:
    custom:
      category: setParameters
    parameters:
      quickModeZ1: 0
      quickModeZ2: 0
      tempSelZ3: -18
  startProgram:
    ancillaryParameters:
      nameVariants: series
      programFamily: [dashboard]
      remoteActionable: 1
      remoteVisible: 1
      zone: [fridge]
    custom:
      program: quick_cool
    parameters:
      quickModeZ1: {"@tempSelZ3":{"4":"1","default":"0"}}
  statistics:
    mostUsedPrograms:
    mostUsedRecipes:
    programsCounter: 0
  stopProgram:
    parameters:
      quickModeZ1: 0
      quickModeZ2: 0
commands:
  settings:
    category:
      - setConfig
      - setParameters
    tempSelZ3:
      - 4
      - -16
      - -18
      - -20
      - -24
  startProgram:
    program:
      - eco_mode
      - quick_cool
      - shock_freeze
      - super_freeze
    programFamily:
      - dashboard
    zone:
      - fridge
versions:
  hon: 0.13.0
  pyhOn: 0.16.0
```
