### ISSUE TITLE
Add steam function washing machine HW90-B14959U1

### ISSUE THREAD

**Issue by StrandmonYellow** [Andre0512/hon#180]
My Feature resquest is not particularly related to a problem. 

I would like a button in the HA UI to add the steam fase at the end of the program because my model does support the steam function. Just like there are switches for the "keep fresh" or "pre-wash" functions. 

![image](https://github.com/Andre0512/hon/assets/99552124/363a8394-4ae9-40e7-a1be-753cdd17b3f8)

**Device Log**
```
data:
  additional_data:
    dictionaryId: 150
    options: haier_SoakPrewashSelection
  appliance:
    PK: user#eu-west-1:b45be597-807d-4fcc-9fdd-3c561a0f87e8
    SK: app#xx-xx-xx-xx-xx-xx
    applianceId: xx-xx-xx-xx-xx-xx#1970-01-01T00:00:00.0Z
    applianceModelId: 950
    applianceStatus: 1
    applianceTypeId: 1
    applianceTypeName: WM
    attributes:
      acuVersion: 0.0.0
      chipset: 1
      dictionaryId: 150
      eppParserSet: 1
      fwLabel: iotfw_epp
      idfVersion: 4.4.4
      kernelVersion: 10.4.3
      lang: it-IT
      uiVersion: 22.02.12
    brand: haier
    code: CEAAHRE0200
    connectivity: wifi|ble
    defaultWarrantyYears: 2
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 1970-01-01T00:00:00.0Z
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 5.15.0
    id: 950
    lastUpdate: 1970-01-01T00:00:00.0Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: HW90-B14959U1_BNL
    nickName: Wasmachine XXX
    purchaseDate: 1970-01-01T00:00:00.0Z
    sections:
      chatbot: True
      demo: True
      double_pairing_hidden: True
      ecoDelayStart: True
      snap_wash: True
    series: 959
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
    waterHard: 1
  attributes:
    active: True
    activity:
      activityExecutionStarted: 2024-03-09 12:10:02
      activityStarted: 1970-01-01T00:00:00.0Z
      applianceTypeName: WM
      attributes:
        antiWrinkle: 1
        autoDetergentStatus: 0
        autoSoftenerStatus: 0
        channel: appliance
        delayStatus: 0
        dirtyLevel: 0
        dryLevel: 0
        dryProgFlag: 0
        dryTime: 0
        liquidDetergentDose: 3
        nightWashStatus: 0
        origin: dashboard
        permanentPressStatus: 0
        powderDetergentDose: 3
        prCode: 116
        programCluster: traditional
        programFamily: [dashboard]
        programIntensity: standard
        programName: HQD_SYNTHETIC_AND_COLOURED
        programType: W
        remainingTimeMM: 144
        remoteCtrValid: 0
        spinSpeed: 600
        suggestedLoadW: RL50
        temp: 60
      category: CYCLE
      macAddress: xx-xx-xx-xx-xx-xx
      resultCode: 0
      ttl: 1717762202
    commandHistory:
      command:
        ancillaryParameters:
          antiWrinkle: 0
          energyLabel: 4
          liquidDetergentDose: 1
          powderDetergentDose: 1
          prPosition: 24
          programCluster: delicate
          programFamily: [hidden|dashboard]
          programIntensity: delicate
          programType: W
          remoteActionable: 1
          remoteVisible: 1
          suggestedLoadW: 2.25
          tempContribution: 1
        applianceOptions:
          haier_SoakPrewashSelection: haier_SoakPrewashSelection
        applianceType: WM
        attributes:
          channel: mobileApp
          energyLabel: 0
          origin: standardProgram
        commandName: startProgram
        device:
          appVersion: 2.6.5
          deviceModel: pyhOn
          mobileId: homassistant
          mobileOs: android
          osVersion: 999
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          antiAllergyStatus: 0
          autoDetergentStatus: 0
          autoDisinfectantStatus: 0
          autoSoftenerStatus: 0
          cloudProgId: 255
          cloudProgSrc: 2
          creaseResistSoakStatus: 0
          delayStatus: 0
          delayTime: 0
          detergentBStatus: 0
          dryLevel: 0
          dryProgFlag: 0
          dryTime: 0
          energySavingStatus: 0
          haier_ConstantTempStatus: 1
          haier_MainWashRotateTime: 30
          haier_MainWashSpeed: 90
          haier_MainWashStopTime: 30
          haier_MainWashWaterLevel: 4
          haier_RinseRotateTime: 30
          haier_RinseSpeed: 90
          haier_RinseStopTime: 30
          haier_SoakPrewashRotateTime: 0
          haier_SoakPrewashSelection: 0
          haier_SoakPrewashSpeed: 0
          haier_SoakPrewashStopTime: 0
          haier_SoakPrewashTemperature: 0
          haier_SoakPrewashTime: 0
          highWaterLevelStatus: 0
          intelligenceStatus: 0
          lockStatus: 0
          mainWashTime: 10
          nightWashStatus: 0
          operationName: grOnlineWash
          permanentPressStatus: 0
          prCode: 90
          rinseIterationTime: 5
          rinseIterations: 2
          soakWashStatus: 0
          speedUpStatus: 0
          spinSpeed: 600
          strongStatus: 0
          temp: 30
          texture: 22
          uvSterilizationStatus: 0
          voiceStatus: 0
          washerDryIntensity: 1
          weight: 2
        programName: PROGRAMS.WM_WD.HQD_DELICATE_CRADLE
        timestamp: 1970-01-01T00:00:00.0Z
        transactionId: xx-xx-xx-xx-xx-xx_1970-01-01T00:00:00.0Z
      timestampAccepted: 1970-01-01T00:00:00.0Z
      timestampExecuted: 1970-01-01T00:00:00.0Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 1970-01-01T00:00:00.0Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1709986155202
    parameters:
      actualWeight: 1
      airWashTempLevel: 0
      airWashTime: 0
      antiAllergyStatus: 0
      autoDetergentStatus: 0
      autoDisinfectantStatus: 0
      autoSoftenerStatus: 0
      buzzerDisabled: 1
      buzzerDisabledCurrent: 0
      clothesAnionStatus: 0
      cloudProgId: 0
      cloudProgSrc: 1
      creaseResistSoakStatus: 0
      currentElectricityUsed: 0.34
      currentWashCycle: 39
      currentWaterUsed: 8
      debugEnabled: 0
      defSetAllowed: 0
      delayStatus: 0
      detWarn: 0
      detergentBStatus: 0
      detergentPercent: 0
      detergentType: 1
      dirtyLevel: 0
      doorLockStatus: 1
      doorStatus: 0
      dryCleaningNeeded: 0
      dryLevel: 0
      dryProgFlag: 0
      dryStatus: 0
      dryTime: 0
      energySavingStatus: 0
      errors: 00
      forceDelete: 0
      haier_DetergentWeight: 0
      haier_SoftenerWeight: 0
      highTransRate: 1
      highWaterLevelStatus: 0
      intelligenceStatus: 0
      laundryCycleStatus: 1
      lockStatus: 0
      loosenStatus: 0
      machMode: 2
      message: 0
      nightWashStatus: 0
      pause: 0
      permanentPressStatus: 0
      prCode: 116
      prPhase: 2
      program1: 2
      program10: 0
      program11: 0
      program12: 0
      program13: 0
      program14: 0
      program15: 0
      program16: 0
      program17: 1
      program18: 2
      program19: 0
      program2: 0
      program20: 1
      program21: 3
      program22: 0
      program23: 0
      program24: 1
      program25: 0
      program3: 0
      program4: 0
      program5: 0
      program6: 8
      program7: 13
      program8: 7
      program9: 0
      programStats: 2;;;;;8;d;7;;;;;;;;;1;2;;1;3;;;1
      purifiedWashStatus: 0
      remainingMainWashTime: 76
      remainingRinseIterations: 2
      remainingStandbyTime: 0
      remainingTimeMM: 110
      remoteCtrValid: 0
      shoesAnionStatus: 0
      soakWashStatus: 0
      softWarn: 0
      speedUpStatus: 0
      spinSpeed: 600
      stainType: 0
      standbyTimeExtended: 1
      statusSyncRate: 1440
      stdTransRate: 1
      steamStatus: 0
      strongStatus: 0
      temp: 60
      temp0to30: 25
      temp40: 3
      temp60to90: 10
      testCmdReceiveStatus: 0
      texture: 6
      totalElectricityUsed: 24.46
      totalWashCycle: 39
      totalWaterUsed: 1525
      transMode: 0
      uvSterilizationStatus: 0
      voiceModuleDataDef: 130
      voiceModuleOnOffStatus: 1
      voiceModuleVolume: 0
      voiceModuleWakeStatus: 0
      voiceModuleWakeUp: 0
      voiceStatus: 0
      washSpeed: 0
      washerDryIntensity: 1
      weight: 1
    pause: False
    programName: No Program
    resultCode: 0
  pauseProgram:
    parameters:
      pause: 1
  resumeProgram:
    parameters:
      pause: 0
  settings:
    custom:
      category: setConfig
    parameters:
      httpEndpoint: 0
      mqttEndpoint: 0
  startProgram:
    ancillaryParameters:
      antiWrinkle: 0
      energyLabel: 4
      liquidDetergentDose: 1
      powderDetergentDose: 1
      prPosition: 24
      programCluster: delicate
      programFamily: [hidden|dashboard]
      programIntensity: delicate
      programType: W
      remoteActionable: 1
      remoteVisible: 1
      suggestedLoadW: 2.25
      tempContribution: 1
    custom:
      program: hqd_delicate_cradle
    parameters:
      antiAllergyStatus: 0
      autoDetergentStatus: 0
      autoDisinfectantStatus: 0
      autoSoftenerStatus: 0
      cloudProgId: 255
      cloudProgSrc: 2
      creaseResistSoakStatus: 0
      delayStatus: 0
      delayTime: 0
      detergentBStatus: 0
      dryLevel: 0
      dryProgFlag: 0
      dryTime: 0
      energySavingStatus: 0
      haier_ConstantTempStatus: 1
      haier_MainWashRotateTime: 30
      haier_MainWashSpeed: 90
      haier_MainWashStopTime: 30
      haier_MainWashWaterLevel: 4
      haier_RinseRotateTime: 30
      haier_RinseSpeed: 90
      haier_RinseStopTime: 30
      haier_SoakPrewashRotateTime: 0
      haier_SoakPrewashSelection: 0
      haier_SoakPrewashSpeed: 0
      haier_SoakPrewashStopTime: 0
      haier_SoakPrewashTemperature: 0
      haier_SoakPrewashTime: 0
      highWaterLevelStatus: 0
      intelligenceStatus: 0
      lockStatus: 0
      mainWashTime: 10
      nightWashStatus: 0
      operationName: grOnlineWash
      permanentPressStatus: 0
      prCode: 90
      rinseIterationTime: 5
      rinseIterations: 2
      soakWashStatus: 0
      speedUpStatus: 0
      spinSpeed: 600
      strongStatus: 0
      temp: 30
      texture: 22
      uvSterilizationStatus: 0
      voiceStatus: 0
      washerDryIntensity: 1
      weight: 2
    remainingTimes:
      remainingTime: 47
  statistics:
    drawerCleaning:
      count: 36
      percentage: 33
      remaining: 74
      tot: 110
    drumCleaning:
      count: 36
      percentage: 33
      remaining: 74
      tot: 110
    filterCleaning:
      count: 36
      percentage: 36
      remaining: 64
      tot: 100
    lastCheckup: None
    loadingPercentage:
      - current: 5
        date: 1970-01-01T00:00:00.0Z
        max: 9
      - current: 2
        date: 1970-01-01T00:00:00.0Z
        max: 4.5
      - current: 5
        date: 1970-01-01T00:00:00.0Z
        max: 4.5
      - current: 1
        date: 1970-01-01T00:00:00.0Z
        max: 0
      - current: 5
        date: 1970-01-01T00:00:00.0Z
        max: 9
    mostUsedPrograms:
      - count: 5
        prCode: 116
        prPosition: 8
        programName: PROGRAMS.WM_WD.IOT_WASH_WHITES
        programType: W
      - count: 3
        prCode: 115
        prPosition: 7
        programName: PROGRAMS.WM_WD.IOT_WASH_BED_LINEN
        programType: W
      - count: 3
        prCode: 115
        prPosition: 7
        programName: PROGRAMS.WM_WD.IOT_WASH_BATHROBE
        programType: W
      - count: 2
        prCode: 115
        prPosition: 7
        programName: PROGRAMS.WM_WD.HQD_COTTONS
        programType: W
      - count: 2
        prCode: 116
        prPosition: 8
        programName: PROGRAMS.WM_WD.IOT_WASH_DARK
        programType: W
    programsCounter: 36
    resultCode: 0
    temperatureUsage:
      temp0to30: 63.888888888888886
      temp40: 8.333333333333332
      temp60to90: 27.77777777777778
  stopProgram:
    parameters:
      onOffStatus: 0
commands:
  settings:
    category:
      - setConfig
  startProgram:
    delayStatus:
      max: 1
      min: 0
      step: 1
    delayTime:
      max: 1410
      min: 0
      step: 30
    energyLabel:
      max: 5
      min: 3
      step: 1
    haier_SoakPrewashSelection:
      max: 2
      min: 0
      step: 2
    mainWashTime:
      max: 120
      min: 5
      step: 5
    nightWashStatus:
      max: 1
      min: 0
      step: 1
    permanentPressStatus:
      max: 1
      min: 0
      step: 1
    program:
      - hqd_20_degrees
      - hqd_allergy
      - hqd_autoclean
      - hqd_babycare
      - hqd_checkup
      - hqd_cottons
      - hqd_delicate_cradle
      - hqd_duvet
      - hqd_eco_40_60_degrees
      - hqd_handwash_wool
      - hqd_mix
      - hqd_quick_15
      - hqd_quick_wash_57
      - hqd_refresh
      - hqd_rinse
      - hqd_shirts
      - hqd_smart
      - hqd_spin
      - hqd_sport
      - hqd_synthetic_and_coloured
      - iot_wash_anti_mites
      - iot_wash_ariel_clean_cycle
      - iot_wash_ariel_cold_cycle
      - iot_wash_ariel_fresh_cycle
      - iot_wash_baby_sanitizer
      - iot_wash_backpacks
      - iot_wash_bathrobe
      - iot_wash_bed_linen
      - iot_wash_bleaching
      - iot_wash_blood_stains
      - iot_wash_cashmere
      - iot_wash_chocolate_stains
      - iot_wash_cold_wash
      - iot_wash_colored
      - iot_wash_colored_anti_stain
      - iot_wash_colored_delicate
      - iot_wash_coloured
      - iot_wash_cotton
      - iot_wash_cuddly_toys
      - iot_wash_curtains
      - iot_wash_dark
      - iot_wash_delicate
      - iot_wash_delicate_antiallergy
      - iot_wash_delicate_colors
      - iot_wash_delicate_dark
      - iot_wash_delicate_tablecloths
      - iot_wash_delicate_whites
      - iot_wash_denim_jeans
      - iot_wash_diving_suits
      - iot_wash_down_jackets
      - iot_wash_fruit_stains
      - iot_wash_handwash
      - iot_wash_handwash_colored
      - iot_wash_handwash_dark
      - iot_wash_lingerie
      - iot_wash_masks_refresh
      - iot_wash_masks_sanification
      - iot_wash_mats
      - iot_wash_men_s_trousers
      - iot_wash_mixed
      - iot_wash_new_clothes
      - iot_wash_perfect_white
      - iot_wash_pets
      - iot_wash_pets_hair_removal
      - iot_wash_pets_odours_stains_removal
      - iot_wash_rapid_14
      - iot_wash_rapid_30
      - iot_wash_rapid_44
      - iot_wash_rapid_59
      - iot_wash_resistant_colored
      - iot_wash_resistant_dark
      - iot_wash_resistant_whites
      - iot_wash_rinse
      - iot_wash_silk
      - iot_wash_ski_suit
      - iot_wash_spin
      - iot_wash_sport
      - iot_wash_sport_anti_odor
      - iot_wash_swimsuits_and_bikinis
      - iot_wash_synthetic
      - iot_wash_tablecloths
      - iot_wash_technical_fabrics
      - iot_wash_technical_jackets
      - iot_wash_trainers
      - iot_wash_whites
      - iot_wash_wine_stains
      - iot_wash_wool
    programCluster:
      - traditional
      - eco
      - traditional_eco
    programFamily:
      - hidden
      - guided
      - dashboard
      - hidden_guided_dashboard
    rinseIterations:
      max: 5
      min: 0
      step: 1
    spinSpeed:
      - 0
      - 400
      - 600
      - 800
      - 1000
      - 1200
      - 1400
    temp:
      - 0
      - 20
      - 30
      - 40
      - 60
      - 90
versions:
  hon: 0.13.0
  pyhOn: 0.16.0

```

**Data Archive**
[wm_950.zip](https://github.com/Andre0512/hon/files/14546269/wm_950.zip)
