### ISSUE TITLE
Add support for XIB 3B2SFS-80 dishwasher

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#21]
This error originated from a custom integration.

Logger: custom_components.hon.button
Source: custom_components/hon/button.py:83
Integration: Haier hOn (documentation, issues)
First occurred: 18:33:57 (1 occurrences)
Last logged: 18:33:57

```
data:
  appliance:
    applianceId: 12-34-56-78-90-ab#2022-07-02T13:40:31Z
    applianceModelId: 874
    applianceStatus: 1
    applianceTypeId: 9
    applianceTypeName: DW
    attributes:
      acuVersion: 0.0.0
      chipset: ESP32D0WDQ5
      dictionaryId: 292
      lang: it-IT
      uiVersion: 5.5.0
    brand: haier
    connectivity: wifi|ble
    eepromId: 812
    eepromName: 70010344
    enrollmentDate: 2022-07-02T13:40:31.270Z
    firstEnrollment: False
    firstEnrollmentTBC: False
    fwVersion: 5.5.0
    id: 874
    lastUpdate: 2022-07-02T13:40:42Z
    macAddress: 12-34-56-78-90-ab
    modelName: XIB 3B2SFS-80
    purchaseDate: 2022-07-01T23:00:00.000Z
    sections:
      chatbot: True
      ecoDelayStart: True
    series: haier2021
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/12-34-56-78-90-ab
        - $aws/events/presence/connected/12-34-56-78-90-ab
        - haier/things/12-34-56-78-90-ab/event/appliancestatus/update
        - haier/things/12-34-56-78-90-ab/event/discovery/update
  attributes:
    activity:
    commandHistory:
      command:
        ancillaryParameters:
          ecoDelayStart: 1
          ecoIndex: 3
          ecoIndexOpt3: undefined
          ecoIndexOpt4: undefined
          ecoIndexOpt5: undefined
          energyLabel: 3
          functionalId: 5
          programFamily: [dashboard|guided]
          programRules: [object Object]
          programType: WD
          remainingTime: 125
          remoteActionable: 1
          remoteVisible: 1
          soilSensor: 1
          suggestedLoadD: 13
          temp: 55
          waterEfficiency: 3
          waterSaving: 68
        applianceOptions:
          opt1: threeInOne
          opt2: ecoExpress
          opt3: halfLoad
          opt4: extraDry
          opt5: openDoor
          opt6: addDish
        applianceType: DW
        attributes:
          channel: mobileApp
          energyLabel: 3
          origin: lastProgram
          prStr: Auto Sensor
        commandName: startProgram
        device:
          appVersion: 1.54.9
          deviceModel: iPhone15,2
          mobileId: 80DC0C44-2C44-49A6-81B0-1190B8690656
          mobileOs: ios
          osVersion: 16.3.1
        macAddress: 12-34-56-78-90-ab
        parameters:
          checkUpStatus: 0
          delayTime: 0
          dryLevel: 0
          extraDry: 0
          halfLoad: 0
          onOffStatus: 1
          openDoor: 0
          prCode: 16
          prPosition: 10
        programName: PROGRAMS.DW.AUTO_SENSOR_SOIL
        timestamp: 2023-04-12T13:10:19.208Z
        transactionId: 12-34-56-78-90-ab_2023-04-12T13:10:19.208Z
      timestampAccepted: 2023-04-12T13:10:22.1Z
      timestampExecuted: 2023-04-12T13:10:23.1Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 2023-04-12T07:36:32Z
      macAddress: 12-34-56-78-90-ab
      timestampEvent: 1681284992330
    parameters:
      addDish: 1
      addDishStatus: 0
      armStatus: 0
      buzzerDisabled: 0
      cameraStatus: 0
      checkUpStatus: 0
      delayTime: 0
      doorStatus: 1
      ecoExpress: 0
      errors: 00
      extraDry: 0
      halfLoad: 0
      lang: 2
      lastCycleSavingStatus: 0
      macAddressCamera:
      machMode: 7
      openDoor: 0
      photoSessionStatus: 0
      prCode: 16
      prCodeSuggest: 0
      prPhase: 5
      prPosition: 10
      program1: 198
      program10: 18
      program11: 0
      program12: 0
      program13: 0
      program14: 0
      program15: 0
      program16: 0
      program17: 0
      program18: 0
      program19: 0
      program2: 0
      program20: 0
      program21: 0
      program3: 0
      program4: 86
      program5: 0
      program6: 0
      program7: 0
      program8: 6
      program9: 5
      remainingTimeMM: 0
      remoteCtrValid: 1
      rinseAidStatus: 0
      saltStatus: 1
      specialAutomaticStatus: 0
      temp45to55: 154
      temp60to65: 92
      temp70to75: 5
      threeInOne: 0
      waterHard: 4
    resultCode: 0
  startProgram:
    checkUpStatus: 0
    delayTime: 0
    extraDry: 0
    halfLoad: 0
    onOffStatus: 1
    openDoor: 0
    prCode: 10
    prPosition: 4
    prStr: 0
    program: iot_dreft_quick_cycle
    waterHard: 4
  statistics:
    mostUsedPrograms:
      - count: 93
        prCode: 8
        prPosition: 1
        programName: PROGRAMS.DW.ECO_BLDC
      - count: 55
        prCode: 10
        prPosition: 4
        programName: PROGRAMS.DW.IOT_FAIRY_QUICK_CYCLE
      - count: 20
        prCode: 16
        prPosition: 10
        programName: PROGRAMS.DW.AUTO_SENSOR_SOIL
      - count: 3
        prCode: 10
        prPosition: 4
        programName: PROGRAMS.DW.RAPID_59
      - count: 2
        prCode: 3
        prPosition: 8
        programName: PROGRAMS.DW.INTENSIVE_RAPID
    mostUsedRecipes:
    programsCounter: 149
    temperatureUsage:
      temp45to55: 61
      temp60to65: 36
      temp70to75: 2
  stopProgram:
    onOffStatus: 0 commands:
  startProgram:
    delayTime:
      max: 1410
      min: 0
      step: 30
    program:
      - auto_sensor_soil
      - auto_universal_plus_soil
      - auto_universal_soil
      - dishwasher_care
      - eco_bldc
      - gentle_wash
      - glassware
      - hygiene_plus
      - intensive_rapid
      - iot_auto_universal_soil
      - iot_auto_wash_soil
      - iot_baby_care
      - iot_breakfast
      - iot_checkup
      - iot_china_crystals
      - iot_classe_a_59
      - iot_cocktail_glasses_soil
      - iot_daily_care_soil
      - iot_delicate
      - iot_dinner_for_two_soil
      - iot_dreft_quick_cycle
      - iot_eco_bldc
      - iot_extra_hygiene
      - iot_fairy_quick_cycle
      - iot_happy_hour
      - iot_party_soil
      - iot_pizza_menu_soil
      - iot_plastic_tupperware
      - iot_porcelain
      - iot_pot_&_pans_soil
      - iot_power_mix_wash_soil
      - iot_prewash
      - iot_pyrex_and_glassware
      - iot_rapid_29
      - iot_rapid_39
      - iot_single
      - iot_steam
      - iot_super_flash
      - iot_super_wash
      - iot_turbopower
      - iot_wok_grids_maxi_pans_soil
      - prewash
      - rapid_29
      - rapid_39
      - rapid_59
      - steam_plus
      - ultra_silence
    waterHard:
      max: 7
      min: 0
      step: 1
  stopProgram:
```

If I can provide any other info, please let me know
