### ISSUE TITLE
WH - ES50V- TF7W(EU) - Water Heater

### ISSUE THREAD

**Issue by straga** [Andre0512/hon#268]
```
========== WH - ES50V- TF7W(EU) ==========
data:
  additional_data:
    dictionaryId: 489
  appliance:
    PK: 
    SK: 
    applianceId: 
    applianceModelId: 13519
    applianceStatus: 1
    applianceTypeId: 10
    applianceTypeName: WH
    attributes:
      acuVersion: 0.0.0
      chipset: 1
      dictionaryId: 489
      eppParserSet: 1
      fwLabel: iotfw_epp
      idfVersion: 4.4.5
      kernelVersion: 10.4.3
      lang: it-IT
      uiVersion: 19.08.09
    brand: haier
    code: GA0SZ5E0M00
    connectivity: wifi|ble
    coords:
      lat: 
      lng: 
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 
    firstEnrollment: True
    firstEnrollmentTBC: True
    fwVersion: 5.19.0
    id: 13519
    lastUpdate: 
    macAddress: 
    modelName: ES50V- TF7W(EU)
    sections:
      chatbot: True
      double_pairing_hidden: True
      epp_enabled: False
      guided_washing: True
      hints: True
      inventory: True
    serialNumber: 
    series: tf7
    sfPersonAccountId: 
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/...
        - $aws/events/presence/connected/...
        - haier/things/.../event/appliancestatus/update
        - haier/things/.../event/discovery/update
  attributes:
    active: False
    activity:
    lastConnEvent:
      category: CONNECTED
      instantTime: 
      macAddress: 
      timestampEvent: 
    parameters:
      3dRunningStatus: 0
      anodeMaintenanceStatus: 0
      autoCruiseSatus: 0
      autoPowerOffStatus: 0
      bathMode: 0
      date: 2000-12-01
      debugEnabled: 0
      dynamicExpansionStatus: 0
      ecoSmartStatus: 0
      emValveStatus: 0
      energySavingStatus: 0
      errors: 00
      filterChangeStatus: 0
      filterRemainingStatus: 0
      fireWallAlarmStatus: 0
      fireWallStatus: 0
      forceDelete: 0
      heatKeepingStatus: 0
      heatingCruiseSatus: 0
      heatingModeSupported: 0
      heatingStatus: 1
      highTransRate: 1
      instantHeatingStatus: 0
      leakageTestExist: 0
      machMode: 0
      manual3dStatus: 1
      mgTestModuleExist: 0
      multiPeopleMode: 0
      nightMode: 0
      onOffStatus: 0
      operationSource: 2
      power: 0
      powerGears: 3
      powerRated: 3000
      powerSettingSupported: 1
      productType: 0
      productVolume: 50
      rapidMode: 0
      remainingTimeDDSterilization: 0
      remainingTimeMMHeating: 0
      remainingTimeMMWash: 0
      remainingVolumeHotWater: 255
      runningMode: 1
      runningModeSupported: 1
      sceneSettingSupported: 0
      smartMode: 0
      smartTestStatus: 0
      statusSyncRate: 1440
      stdTransRate: 3600
      sterilizationResult: 0
      sterilizationStatusReminder: 0
      tankMaintenanceStatus: 0
      temp: 18
      tempConstant: 0
      tempIn: 0
      tempIndoor: -50
      tempOut: 0
      tempOutdoor: -50
      tempSel: 75
      tempZ1: 18
      tempZ2: 18
      time: 00:00
      timerCycleStatus1: 1
      timerCycleStatus2: 1
      timerHH1: 7
      timerHH2: 17
      timerMM1: 0
      timerMM2: 0
      timerMode: 0
      timerResult1: 1
      timerResult2: 1
      timerRunningStatus1: 0
      timerRunningStatus2: 0
      timerSettingSupported: 0
      timerStatus1: 0
      timerStatus10: 0
      timerStatus11: 0
      timerStatus12: 0
      timerStatus2: 0
      timerStatus3: 0
      timerStatus4: 0
      timerStatus5: 0
      timerStatus6: 0
      timerStatus7: 0
      timerStatus8: 0
      timerStatus9: 0
      timerTemp1: 75
      timerTemp2: 75
      totalWorkTime: 0
      transMode: 0
      valleyStartTimeHH: 0
      valleyStartTimeMM: 0
      valleyStopTimeHH: 6
      valleyStopTimeMM: 0
      vastMode: 0
      waterFlow: 0.0
      waterVolume: 0
    programName: No Program
    resultCode: 0
  settings:
    custom:
      category: setParameters
    parameters:
      tempSel: 85
  startProgram:
    ancillaryParameters:
      remoteActionable: 1
      remoteVisible: 1
    custom:
      program: bps
    parameters:
      machMode: 3
      onOffStatus: 1
  statistics:
    mostUsedPrograms:
    mostUsedRecipes:
    programsCounter: 0
  stopProgram:
    parameters:
      onOffStatus: 0
commands:
  settings:
    category:
      - setConfig
      - setParameters
    tempSel:
      max: 85
      min: 30
      step: 1
  startProgram:
    program:
      - bps
      - eco
      - max
      - normal
```
