### ISSUE TITLE
Wine Fridge does not show all entities

### ISSUE THREAD

**Issue by rwez** [Andre0512/hon#65]
Hi I have a Haier HWS247FDU1 Wine Fridge. In previous versions it showed all kinds of information, like temperature and whether the light was on or not. However, since version 0.8.0.-beta9 it only shows a button where I can get information when I press it, and the information only shows op in notifications. It seems that a few entities are missing, I get only 1 entity. No error messages in the log. Please assist. Thank you.
![Screenshot 2023-06-09 at 12 25 37](https://github.com/Andre0512/hon/assets/127622759/28ea447b-2c96-44c2-b5e2-255ba2578ded)
![Screenshot 2023-06-09 at 12 25 17](https://github.com/Andre0512/hon/assets/127622759/adc6c1a0-5bf5-4f04-9ea6-b7dc447e3b64)

**Comment by Andre0512** [comment]
Hi, can I see the notification output?

**Comment by rwez** [comment]
Sure,

Here it is:

```
data:
  additional_data:
  appliance:
    SK_Secondary: WC#carbonFilter#2023-10-22
    applianceCapacity: 42
    applianceId: xx-xx-xx-xx-xx-xx#2023-04-22T11:40:17Z
    applianceModelId: 1503
    applianceStatus: 1
    applianceTypeId: 6
    applianceTypeName: WC
    attributes:
      acuVersion: 22.01.22
      chipset: ESP32D0WDQ5
      dictionaryId: 268
      lang: it-IT
    brand: haier
    code: B408U3E0000
    connectivity: wifi|ble
    defaultWarrantyYears: 2
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 2023-04-22T11:40:17.193Z
    firstEnrollment: False
    firstEnrollmentTBC: False
    fwVersion: 3.8.0
    id: 1503
    lastUpdate: 2023-04-22T11:40:35Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: HWS247FDU1
    nickName: Wine Cellar
    purchaseDate: 2023-04-20T22:00:00.000Z
    sections:
      chatbot: True
      double_pairing_hidden: False
      epp_enabled: False
    series: series60
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
    zone: 1
  attributes:
    activity:
    commandHistory:
      command:
        ancillaryParameters:
        applianceOptions:
        applianceType: WC
        attributes:
          channel: mobileApp
          origin: standardProgram
          prStr: PROGRAMS.WC.WHITE
        commandName: startProgram
        device:
          appVersion: 1.54.9
          deviceModel: exynos2100
          mobileId: 4a4ef26254b6ebd9
          mobileOs: android
          osVersion: 33
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          prCode: 2
          tempSel: 12
        programName: PROGRAMS.WC.WHITE
        timestamp: 2023-04-22T11:44:16.406Z
        transactionId: xx-xx-xx-xx-xx-xx_2023-04-22T11:44:16.407Z
      timestampAccepted: 2023-04-22T11:44:17.8Z
      timestampExecuted: 2023-04-22T11:44:19.0Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 2023-06-05T00:03:32Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1685923412892
    parameters:
      errors: 00
      humidityZ1: 70
      lightStatus: 0
      machMode: 1
      onOffStatus: 1
      prCode: 2
      temp: 11.7
      tempEnv: 19.4
      tempSel: 11.7
      tempUnit: 0
    resultCode: 0
  settings:
    custom:
      category: setParameters
    parameters:
      lightStatus: 0
      sabbathStatus: 0
      tempSel: 5
      tempUnit: 0
  startProgram:
    ancillaryParameters:
      programFamily: [dashboard]
      remoteActionable: 1
      remoteVisible: 1
    custom:
      program: sparkling
    parameters:
      prCode: 3
      tempSel: 8
  statistics:
    carbonFilter:
      lastReplacement: 2023-04-22T11:40:17.193Z
      percentage: 13
      remainingTime: PT7632H24M5.723S
    mostUsedPrograms:
    mostUsedRecipes:
    programsCounter: 0
    resultCode: 0
commands:
  settings:
    category:
      - setConfig
      - setParameters
    lightStatus:
      max: 1
      min: 0
      step: 1
    sabbathStatus:
      max: 1
      min: 0
      step: 1
    tempSel:
      max: 20
      min: 5
      step: 1
    tempUnit:
      max: 1
      min: 0
      step: 1
  startProgram:
    program:
      - iot_champagne
      - iot_dessert
      - iot_fortified
      - iot_rose
      - iot_whisky
      - red
      - sparkling
      - white
    programFamily:
      - dashboard
    tempSel:
      max: 20
      min: 13
      step: 1
rules:
pyhOnVersion: 0.12.3
```
