### ISSUE TITLE
Cannot recall programs or temperature

### ISSUE THREAD

**Issue by wesley2004** [Andre0512/hon#66]
I am on version 8 now
And if i try to recall a program it doesn't start.
Also if i try to recall a temperature it won't start.
This is what i use

`
- alias: 'Airco huiskamer aan'
  trigger:
    platform: state
    entity_id: input_boolean.airco_huiskamer_koelen
    to: 'on'    
  action:
    - service: hon.start_program
      data:
        program: Koelen beneden
      target:
        entity_id: climate.huiskamer
`

or this
`
- alias: 'Airco huiskamer koelen'
  trigger:
    platform: state
    entity_id: input_boolean.airco_huiskamer_koelen
    to: 'on'    
  action:
    - service: hon.climate_set_echo_mode
      data:
        echo_mode: off
      target:
        entity_id: climate.huiskamer
    - service: climate.set_hvac_mode
      data:
        hvac_mode: Cool
      target:
        entity_id: climate.huiskamer
    - delay:
        seconds: 2
    - service: climate.set_temperature
      data:
        temperature: 24
      target:
        entity_id: climate.huiskamer
    - service: input_boolean.turn_off
      entity_id: input_boolean.verwarming
    - service: climate.turn_on
      target:
        entity_id: climate.huiskamer

`

**Comment by Andre0512** [comment]
Hi, these `hon` services aren't supported, you have to use the `swtich.turn_off` service.

**Comment by wesley2004** [comment]
> 

Tnx! I used the other hon application before.
Now I use yours. How does the silent mode works? Also as switch?

**Comment by Andre0512** [comment]
Yes 🙂
You can see all supported switches in settings > Device & Services > Haier hOn

**Comment by wesley2004** [comment]
Thank you, found it. If I put silent mode it automatically switches back and didn’t work

**Comment by Andre0512** [comment]
Can you show me your [device data](https://github.com/Andre0512/hon#read-out-device-data)

**Comment by wesley2004** [comment]
i have problems with the integration.
First it worked, but now it doesn't startup.
I also tried new version but doesn't startup again

**Comment by Andre0512** [comment]
Do you get any error message?

**Comment by wesley2004** [comment]
integration cannot be loaded and other time configuration failed

**Comment by Andre0512** [comment]
Can you check the messages in Settings -> System -> Logs ?

**Comment by Andre0512** [comment]
This is the problem, maybe you edited something manual or an update was interrupted 🤔
If you use hacs, delete the hon dir (`/config/custom_components/hon/`) and install it again with hacs.

**Comment by wesley2004** [comment]
i tried to delete it.
after that i installed new integrations.
but i cannot add it, because its not in the list
so strange!

**Comment by wesley2004** [comment]
oh i didnt deleted the dir, i try again

**Comment by wesley2004** [comment]
again not successful.
Error setting up entry overalmailen@gmail.com for hon
22:35:27 – (FOUT) Haier hOn (aangepaste integratie) - bericht kwam voor het eerst om 22:34:14 en verschijnt 3 keer
hOn Authentication Error 1 401 - https://account2.hon-smarthome.com/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAYjAxA2kMDAwMDAwMDAwMDAwMDAwAAAA9JF6rxdV5eVrEo1riAzJy-6d-qh8o_-JemKiYj50XhW7UJoTbZj24PmFOxd4ZKODLWjj56If6qP0DRP-_1nMkCtB_dQFUKZoeCkptMjyzgY_B_Y7EnadJkBIL1todXrpTR1AjXpt8bqTU-Yh1vNxFrfW4N9hMIP91rlvYmoie8sRR-xfNiXIx9gr3d-UwZtZlhg2tXNG21wxtT2bk-iEjcxTHN1RnoY7o0Hubd6XceL_DOp_F8ozRLGcv5MenMVQzhh2z-_aES4f_eARZV0GhIPjUjYF96mYAHQf2lyxMbhHazSg_HY3l_TaYKTgUiRKrNgDXmiv3pC0uSv44Rj41SHr83scEXbidnga4135t5386u2ZSyrOTel7sEjQhs6_iQ9ies84N-gi6eGTumPMIMk7t4tVJGAa0plJNCvTSwaH_dwDnXvbHI96jqxobETjExIWVAQzTYb9HJfQQ4rAFNCTjlHOP6lm9DMK4-MTuY4GWouc0T-MSELcNtQYBsTuh-H7wfxv3F1u24abVSwJ-Y_px90o_z9UgKuT-lb0koLyQeZY0ea5rFAir4C0u8fbfOSyNn-1f3QaOV2rMC1X1TpGcFoLslBrym9kEO7AaOP5DpRGBH-kivOM3wu4QLAfyDyS6HHKTGNxWy9zPTnd_Rjrfhvzt4G4J2UC6rwB27BpJcILxt_rL43wSsPTmZo4sevXnj68WVpor_afuuzmuej2hsLTOrpunoHnx3JeTuU_&display=touch 2 302 - https://account2.hon-smarthome.com/s/login?display=touch&ec=302&inst=68&startURL=/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYjAxA2kMDAwMDAwMDAwMDAwMDAwAAAA9JF6rxdV5eVrEo1riAzJy-6d-qh8o_-JemKiYj50XhW7UJoTbZj24PmFOxd4ZKODLWjj56If6qP0DRP-_1nMkCtB_dQFUKZoeCkptMjyzgY_B_Y7EnadJkBIL1todXrpTR1AjXpt8bqTU-Yh1vNxFrfW4N9hMIP91rlvYmoie8sRR-xfNiXIx9gr3d-UwZtZlhg2tXNG21wxtT2bk-iEjcxTHN1RnoY7o0Hubd6XceL_DOp_F8ozRLGcv5MenMVQzhh2z-_aES4f_eARZV0GhIPjUjYF96mYAHQf2lyxMbhHazSg_HY3l_TaYKTgUiRKrNgDXmiv3pC0uSv44Rj41SHr83scEXbidnga4135t5386u2ZSyrOTel7sEjQhs6_iQ9ies84N-gi6eGTumPMIMk7t4tVJGAa0plJNCvTSwaH_dwDnXvbHI96jqxobETjExIWVAQzTYb9HJfQQ4rAFNCTjlHOP6lm9DMK4-MTuY4GWouc0T-MSELcNtQYBsTuh-H7wfxv3F1u24abVSwJ-Y_px90o_z9UgKuT-lb0koLyQeZY0ea5rFAir4C0u8fbfOSyNn-1f3QaOV2rMC1X1TpGcFoLslBrym9kEO7AaOP5DpRGBH-kivOM3wu4QLAfyDyS6HHKTGNxWy9zPTnd_Rjrfhvzt4G4J2UC6rwB27BpJcILxt_rL43wSsPTmZo4sevXnj68WVpor_afuuzmuej2hsLTOrpunoHnx3JeTuU_%26display%3Dtouch 3 301 - https://account2.hon-smarthome.com/s/login/?display=touch&ec=302&inst=68&startURL=/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYjAxA2kMDAwMDAwMDAwMDAwMDAwAAAA9JF6rxdV5eVrEo1riAzJy-6d-qh8o_-JemKiYj50XhW7UJoTbZj24PmFOxd4ZKODLWjj56If6qP0DRP-_1nMkCtB_dQFUKZoeCkptMjyzgY_B_Y7EnadJkBIL1todXrpTR1AjXpt8bqTU-Yh1vNxFrfW4N9hMIP91rlvYmoie8sRR-xfNiXIx9gr3d-UwZtZlhg2tXNG21wxtT2bk-iEjcxTHN1RnoY7o0Hubd6XceL_DOp_F8ozRLGcv5MenMVQzhh2z-_aES4f_eARZV0GhIPjUjYF96mYAHQf2lyxMbhHazSg_HY3l_TaYKTgUiRKrNgDXmiv3pC0uSv44Rj41SHr83scEXbidnga4135t5386u2ZSyrOTel7sEjQhs6_iQ9ies84N-gi6eGTumPMIMk7t4tVJGAa0plJNCvTSwaH_dwDnXvbHI96jqxobETjExIWVAQzTYb9HJfQQ4rAFNCTjlHOP6lm9DMK4-MTuY4GWouc0T-MSELcNtQYBsTuh-H7wfxv3F1u24abVSwJ-Y_px90o_z9UgKuT-lb0koLyQeZY0ea5rFAir4C0u8fbfOSyNn-1f3QaOV2rMC1X1TpGcFoLslBrym9kEO7AaOP5DpRGBH-kivOM3wu4QLAfyDyS6HHKTGNxWy9zPTnd_Rjrfhvzt4G4J2UC6rwB27BpJcILxt_rL43wSsPTmZo4sevXnj68WVpor_afuuzmuej2hsLTOrpunoHnx3JeTuU_%26display%3Dtouch 4 200 - https://account2.hon-smarthome.com/s/login/?language=en_US&display=touch&ec=302&inst=68&startURL=%2Fsetup%2Fsecur%2FRemoteAccessAuthorizationPage.apexp%3Fsource%3DCAAAAYjAxA2kMDAwMDAwMDAwMDAwMDAwAAAA9JF6rxdV5eVrEo1riAzJy-6d-qh8o_-JemKiYj50XhW7UJoTbZj24PmFOxd4ZKODLWjj56If6qP0DRP-_1nMkCtB_dQFUKZoeCkptMjyzgY_B_Y7EnadJkBIL1todXrpTR1AjXpt8bqTU-Yh1vNxFrfW4N9hMIP91rlvYmoie8sRR-xfNiXIx9gr3d-UwZtZlhg2tXNG21wxtT2bk-iEjcxTHN1RnoY7o0Hubd6XceL_DOp_F8ozRLGcv5MenMVQzhh2z-_aES4f_eARZV0GhIPjUjYF96mYAHQf2lyxMbhHazSg_HY3l_TaYKTgUiRKrNgDXmiv3pC0uSv44Rj41SHr83scEXbidnga4135t5386u2ZSyrOTel7sEjQhs6_iQ9ies84N-gi6eGTumPMIMk7t4tVJGAa0plJNCvTSwaH_dwDnXvbHI96jqxobETjExIWVAQzTYb9HJfQQ4rAFNCTjlHOP6lm9DMK4-MTuY4GWouc0T-MSELcNtQYBsTuh-H7wfxv3F1u24abVSwJ-Y_px90o_z9UgKuT-lb0koLyQeZY0ea5rFAir4C0u8fbfOSyNn-1f3QaOV2rMC1X1TpGcFoLslBrym9kEO7AaOP5DpRGBH-kivOM3wu4QLAfyDyS6HHKTGNxWy9zPTnd_Rjrfhvzt4G4J2UC6rwB27BpJcILxt_rL43wSsPTmZo4sevXnj68WVpor_afuuzmuej2hsLTOrpunoHnx3JeTuU_%26display%3Dtouch&System=IoT_Mobile_App&RegistrationSubChannel=hOn 5 200 - https://account2.hon-smarthome.com/s/sfsites/aura?r=3&other.LightningLoginCustom.login=1 ERROR - 200 - https://account2.hon-smarthome.com/s/sfsites/aura?r=3&other.LightningLoginCustom.login=1 =============== Response =============== {"actions":[{"id":"79;a","state":"SUCCESS","returnValue":"Your login attempt has failed. Make sure the username and password are correct.","error":[]}],"context":{"mode":"PROD","app":"siteforce:loginApp2","contextPath":"/s/sfsites","pathPrefix":"","fwuid":"c1R3MUZhNldLUm1BS0plaUgwaDhnQWI4T1Q3UVpoR0gtemxDX3B4aTM3bVEyNDQuMjAuMS0yLjQxLjQ","mlr":1,"loaded":{"APPLICATION@markup://siteforce:loginApp2":"Izv9eREiUIuimW-V5PtbgQ"},"globalValueProviders":[{"type":"$Global","values":{"eswConfigDeveloperName":{"writable":true,"defaultValue":""},"isVoiceOver":{"writable":true,"defaultValue":false},"setupAppContextId":{"writable":true,"defaultValue":""},"density":{"writable":true,"defaultValue":""},"srcdoc":{"writable":false,"defaultValue":false},"appContextId":{"writable":true,"defaultValue":""},"dynamicTypeSize":{"writable":true,"defaultValue":""}}}],"enableAccessChecks":true,"apce":1,"dns":"c","lairn":[],"laerc":[],"lav":"58","mna":{"lightning":"interop"},"lff":{"ENABLE_MIXED_SHADOW_MODE":false,"ENABLE_LIGHT_GET_ROOT_NODE_PATCH":true,"DISABLE_LIGHT_DOM_UNSCOPED_CSS":false},"arse":1,"acaf":1,"services":["markup://lightning:configProvider","markup://force:salesforceScopedModuleResolver","markup://force:ldsEngineCreator","markup://instrumentation:locatorService"]},"perfSummary":{"version":"core","request":28,"actions":{"79;a":{"total":25,"db":2}},"actionsTotal":25,"overhead":0}} ========================================
22:35:27 – (FOUT) Haier hOn (aangepaste integratie) - bericht kwam voor het eerst om 22:34:14 en verschijnt 3 keer

**Comment by Andre0512** [comment]
So, the error message is "Your login attempt has failed. Make sure the username and password are correct". Can you double check that your login is correct? 🤔

**Comment by wesley2004** [comment]
i tried 4 times......

**Comment by wesley2004** [comment]
finally, i changed the password in the hon app. after this the integration is working.
now i can check the device settings

**Comment by wesley2004** [comment]
device info entity not available??

**Comment by wesley2004** [comment]
# Example configuration.yaml entry
command_line:
  - binary_sensor:
      command: "cat /proc/sys/net/ipv4/ip_forward"

**Comment by wesley2004** [comment]
```
data:
  additional_data:
  appliance:
    SK_Secondary: AC#selfClean#2022-01-04
    applianceId: xx-xx-xx-xx-xx-xx#2021-08-07T12:09:08Z
    applianceModelId: 340
    applianceStatus: 1
    applianceTypeId: 11
    applianceTypeName: AC
    attributes:
      acuVersion: 06.26.00
      chipset: 1
      dictionaryId: 180
      eppParserSet: 1
      fwLabel: iotfw_epp
      lang: it-IT
      uiVersion: 06.26.00
    brand: haier
    code: AAANW1E0000
    connectivity: wifi|ble
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 2021-08-07T12:09:08.452Z
    fwVersion: 5.12.0
    id: 340
    lastSelfClean: 2023-05-01T07:38:16.091Z
    lastSelfPurify: 2022-07-14T17:21:18.756Z
    lastUpdate: 2022-10-01T07:28:36Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: AS35TADHRA-2
    nickName: Huiskamer
    purchaseDate: 2021-08-06T22:00:00.000Z
    sections:
      chatbot: True
      double_pairing_hidden: True
      epp_enabled: False
    series: tundra
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
    unitConfiguration: 1to1
  attributes:
    activity:
    commandHistory:
      command:
        ancillaryParameters:
        applianceOptions:
        applianceType: AC
        attributes:
          0: P
          1: R
          10: C
          11: .
          12: I
          13: O
          14: T
          15: _
          16: C
          17: O
          18: O
          19: L
          2: O
          3: G
          4: R
          5: A
          6: M
          7: S
          8: .
          9: A
          channel: BeMobile
          origin: scheduling
        commandName: stopProgram
        device:
          appVersion: 1.10.0
          mobileOs: android
          osVersion: 28
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          10degreeHeatingStatus: 0
          ch2oCleaningStatus: 0
          cleaningTimeStatus: 0
          echoStatus: 0
          electricHeatingStatus: 0
          energySavePeriod: 15
          energySavingStatus: 0
          filterChangeStatusCloud: 0
          freshAirStatus: 0
          halfDegreeSettingStatus: 0
          healthMode: 0
          heatAccumulationStatus: 0
          humanSensingStatus: 0
          humidificationStatus: 0
          humiditySel: 30
          intelligenceStatus: 0
          lightStatus: 0
          lockStatus: 0
          machMode: 1
          muteStatus: 0
          onOffStatus: 0
          operationName: grSetDAC
          pm2p5CleaningStatus: 0
          pmvStatus: 0
          rapidMode: 0
          screenDisplayStatus: 0
          selfCleaning56Status: 0
          selfCleaningStatus: 0
          silentSleepStatus: 0
          specialMode: 0
          tempSel: 24.00
          tempUnit: 0
          voiceSignStatus: 0
          voiceStatus: 0
          windDirectionHorizontal: 0
          windDirectionVertical: 5
          windSensingStatus: 0
          windSpeed: 5
        programName: PROGRAMS.AC.IOT_COOL
        timestamp: 2023-06-14T21:01:22.360Z
        transactionId: xx-xx-xx-xx-xx-xx_2023-06-14T21:01:22.360Z
      timestampAccepted: 2023-06-14T21:01:39.8Z
      timestampExecuted: 2023-06-14T21:01:40.7Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 2023-05-16T05:08:23Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1684213703797
    parameters:
      10degreeHeatingStatus: 0
      acType: 0
      airQuality: 0
      ch2oCleaningStatus: 0
      ch2oValueIndoor: 0
      co2ValueIndoor: 0
      compressorCurrent: 51.10
      compressorFrequency: 0
      compressorStatus: 0
      debugEnabled: 0
      defrostStatus: 0
      echoStatus: 0
      electricHeatingStatus: 0
      electricHeatingStatusIndoor: 0
      energySavePeriod: 15
      energySavingStatus: 0
      errAckFlag: 0
      errors: 00
      expansionValveOpenDegree: 88
      fanStatusIndoor: 0
      fanStatusOutdoor: 2
      filterChangeStatusLocal: 0
      fourWayValveStatus: 2
      freshAirStatus: 0
      halfDegreeSettingStatus: 0
      healthMode: 0
      highTransRate: 1
      humanSensingStatus: 0
      humidificationStatus: 0
      humidityIndoor: 0
      humiditySel: 30
      intelligenceStatus: 0
      lightStatus: 0
      lockStatus: 0
      machMode: 1
      machineModeHK: 0
      muteStatus: 0
      onOffStatus: 0
      operationName: 
      operationSource: 3
      pm2p5CleaningStatus: 0
      pm2p5LevelIndoor: 0
      pm2p5ValueIndoor: 0
      pm2p5ValueOutdoor: 0
      pmvStatus: 0
      power: 0
      rapidMode: 0
      screenDisplayStatus: 0
      selfCleaningStatus: 0
      sensingResult: 0
      silentSleepStatus: 0
      specialMode: 0
      statusSyncRate: 1440
      stdTransRate: 3600
      tempAirOutdoor: 20
      tempCoilerIndoor: 22.00
      tempCoilerOutdoor: -64
      tempDefrostOutdoor: 18
      tempInAirOutdoor: -64
      tempIndoor: 24.50
      tempOutdoor: 24.00
      tempSel: 24.00
      tempUnit: 0
      totalElectricityUsed: 0
      totalWorkTime: 0
      transMode: 0
      vocValueIndoor: 0
      windDirectionHorizontal: 0
      windDirectionVertical: 5
      windSpeed: 5
    resultCode: 0
  settings:
    ancillaryParameters:
      programRules: {'selfCleaningStatus': {'$installationType': {'1toN': {'typology': 'fixed', 'fixedValue': '0'}}}, 'selfCleaning56Status': {'$installationType': {'1to1': {'typology': 'fixed', 'fixedValue': '0'}, '1to2': {'typology': 'fixed', 'fixedValue': '0'}, '1toN': {'typology': 'fixed', 'fixedValue': '0'}}}}
    custom:
      category: setParameters
    parameters:
      10degreeHeatingStatus: 0
      ch2oCleaningStatus: 0
      cleaningTimeStatus: 0
      echoStatus: 0
      electricHeatingStatus: 0
      energySavePeriod: 15
      energySavingStatus: 0
      filterChangeStatusCloud: 0
      freshAirStatus: 0
      halfDegreeSettingStatus: 0
      healthMode: 0
      heatAccumulationStatus: 0
      humanSensingStatus: 0
      humidificationStatus: 0
      humiditySel: 30
      intelligenceStatus: 0
      lightStatus: 0
      lockStatus: 0
      machMode: 0
      muteStatus: 0
      onOffStatus: 1
      operationName: grSetDAC
      pm2p5CleaningStatus: 0
      pmvStatus: 0
      rapidMode: 0
      screenDisplayStatus: 1
      selfCleaning56Status: 0
      selfCleaningStatus: 0
      silentSleepStatus: 0
      specialMode: 0
      tempSel: 22
      tempUnit: 0
      voiceSignStatus: 0
      voiceStatus: 0
      windDirectionHorizontal: 0
      windDirectionVertical: 5
      windSensingStatus: 0
      windSpeed: 5
  startProgram:
    ancillaryParameters:
      programRules: {'selfCleaningStatus': {'$installationType': {'1toN': {'typology': 'fixed', 'fixedValue': '0'}}}, 'selfCleaning56Status': {'$installationType': {'1to1': {'typology': 'fixed', 'fixedValue': '0'}, '1to2': {'typology': 'fixed', 'fixedValue': '0'}, '1toN': {'typology': 'fixed', 'fixedValue': '0'}}}}
      remoteActionable: 1
      remoteVisible: 0
    custom:
      program: iot_simple_start
    parameters:
      10degreeHeatingStatus: 0
      ch2oCleaningStatus: 0
      cleaningTimeStatus: 0
      echoStatus: 0
      electricHeatingStatus: 0
      energySavePeriod: 15
      energySavingStatus: 0
      filterChangeStatusCloud: 0
      freshAirStatus: 0
      halfDegreeSettingStatus: 0
      healthMode: 0
      heatAccumulationStatus: 0
      humanSensingStatus: 0
      humidificationStatus: 0
      humiditySel: 30
      intelligenceStatus: 0
      lightStatus: 0
      lockStatus: 0
      machMode: 1
      muteStatus: 0
      onOffStatus: 1
      operationName: grSetDAC
      pm2p5CleaningStatus: 0
      pmvStatus: 0
      rapidMode: 0
      screenDisplayStatus: 1
      selfCleaning56Status: 0
      selfCleaningStatus: 0
      silentSleepStatus: 0
      specialMode: 0
      tempSel: 25
      tempUnit: 0
      voiceSignStatus: 0
      voiceStatus: 0
      windDirectionHorizontal: 0
      windDirectionVertical: 5
      windSensingStatus: 0
      windSpeed: 5
  statistics:
    mostUsedPrograms:
      - count: 1073
        prCode: None
        programName: PROGRAMS.AC.HOME_ASSISTANT
      - count: 102
        prCode: None
        programName: PROGRAMS.AC.IOT_COOL
      - count: 60
        prCode: None
        programName: PROGRAMS.AC.IOT_AUTO
      - count: 44
        prCode: None
        programName: PROGRAMS.AC.IOT_HEAT
      - count: 17
        prCode: None
        programName: PROGRAMS.AC.IOT_DRY
    mostUsedRecipes:
    programsCounter: 0
  stopProgram:
    parameters:
      10degreeHeatingStatus: 0
      ch2oCleaningStatus: 0
      cleaningTimeStatus: 0
      echoStatus: 0
      electricHeatingStatus: 0
      energySavePeriod: 15
      energySavingStatus: 0
      filterChangeStatusCloud: 0
      freshAirStatus: 0
      halfDegreeSettingStatus: 0
      healthMode: 0
      heatAccumulationStatus: 0
      humanSensingStatus: 0
      humidificationStatus: 0
      humiditySel: 30
      intelligenceStatus: 0
      lightStatus: 0
      lockStatus: 0
      machMode: 0
      muteStatus: 0
      onOffStatus: 0
      operationName: grSetDAC
      pm2p5CleaningStatus: 0
      pmvStatus: 0
      rapidMode: 0
      screenDisplayStatus: 1
      selfCleaning56Status: 0
      selfCleaningStatus: 0
      silentSleepStatus: 0
      specialMode: 0
      tempSel: 22
      tempUnit: 0
      voiceSignStatus: 0
      voiceStatus: 0
      windDirectionHorizontal: 0
      windDirectionVertical: 5
      windSensingStatus: 0
      windSpeed: 5
commands:
  settings:
    10degreeHeatingStatus:
      max: 1
      min: 0
      step: 1
    category:
      - setConfig
      - setParameters
    echoStatus:
      max: 1
      min: 0
      step: 1
    machMode:
      - 0
      - 1
      - 2
      - 4
      - 6
    muteStatus:
      max: 1
      min: 0
      step: 1
    rapidMode:
      max: 1
      min: 0
      step: 1
    screenDisplayStatus:
      max: 1
      min: 0
      step: 1
    selfCleaningStatus:
      max: 1
      min: 0
      step: 1
    silentSleepStatus:
      max: 1
      min: 0
      step: 1
    tempSel:
      max: 30
      min: 16
      step: 1
    windDirectionVertical:
      - 2
      - 4
      - 5
      - 6
      - 7
      - 8
    windSpeed:
      - 1
      - 2
      - 3
      - 5
  startProgram:
    10degreeHeatingStatus:
      max: 1
      min: 0
      step: 1
    echoStatus:
      max: 1
      min: 0
      step: 1
    ecoMode:
      max: 1
      min: 0
      step: 1
    machMode:
      - 0
      - 1
      - 2
      - 4
      - 6
    muteStatus:
      max: 1
      min: 0
      step: 1
    program:
      - Koelen beneden
      - Warmte beneden
      - iot_10_heating
      - iot_auto
      - iot_cool
      - iot_dry
      - iot_fan
      - iot_heat
      - iot_self_clean
      - iot_simple_start
    programFamily:
      - maintenance
      - health
      - maintenance_health
    rapidMode:
      max: 1
      min: 0
      step: 1
    remoteActionable:
      max: 1
      min: 0
      step: 1
    remoteVisible:
      max: 1
      min: 0
      step: 1
    screenDisplayStatus:
      max: 1
      min: 0
      step: 1
    selfCleaningStatus:
      max: 1
      min: 0
      step: 1
    silentSleepStatus:
      max: 1
      min: 0
      step: 1
    tempSel:
      max: 30
      min: 16
      step: 1
    windDirectionVertical:
      - 2
      - 4
      - 5
      - 6
      - 7
      - 8
    windSpeed:
      - 1
      - 2
      - 3
      - 5
  stopProgram:
    10degreeHeatingStatus:
      max: 1
      min: 0
      step: 1
    echoStatus:
      max: 1
      min: 0
      step: 1
    machMode:
      - 0
      - 1
      - 2
      - 4
      - 6
    muteStatus:
      max: 1
      min: 0
      step: 1
    rapidMode:
      max: 1
      min: 0
      step: 1
    screenDisplayStatus:
      max: 1
      min: 0
      step: 1
    selfCleaningStatus:
      max: 1
      min: 0
      step: 1
    silentSleepStatus:
      max: 1
      min: 0
      step: 1
    tempSel:
      max: 30
      min: 16
      step: 1
    windDirectionVertical:
      - 2
      - 4
      - 5
      - 6
      - 7
      - 8
    windSpeed:
      - 1
      - 2
      - 3
      - 5
rules:
  startProgram:
    ecoMode:
      1:
        machMode:
          1:
            tempSel: 26
            windDirectionVertical: 3
            windSpeed: 1
          4:
            tempSel: 20
            windDirectionVertical: 3
            windSpeed: 1
pyhOnVersion: 0.13.0
```
