### ISSUE TITLE
Air Purifier HHP50CA011

### ISSUE THREAD

**Issue by ilbeppe83** [Andre0512/hon#72]
Is it possible to add the following air purifier to the integration?

It would be interesting to have at least the air quality values and the filter status.

Below the device informations:
```
data:
  additional_data:
  appliance:
    SK_Secondary: AP#enroll#2021-12-14
    applianceId: xx-xx-xx-xx-xx-xx#2021-12-14T18:33:54Z
    applianceModelId: 132
    applianceStatus: 1
    applianceTypeId: 7
    applianceTypeName: AP
    attributes:
      acuVersion: 0.1.0
      chipset: ESP32D0WDQ5
      dictionaryId: 74
      lang: it-IT
    brand: hoover
    code: 38290207
    connectivity: wifi|ble
    eepromId: 41
    eepromName: no_eeprom
    enrollmentDate: 2021-12-14T18:33:54.782Z
    fwVersion: 1.4.0
    id: 132
    lastUpdate: 2022-10-01T07:28:36Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: HHP50CA011
    nickName: Purificatore d'aria
    purchaseDate: 2021-12-12T23:00:00.000Z
    sections:
      chatbot: True
      double_pairing_hidden: True
    series: h-purifier500
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
  attributes:
    activity:
      activityExecutionStarted: 2023-06-11 17:46:03
      activityStarted: 2023-06-11T17:46:03Z
      applianceTypeName: AP
      attributes:
        airQuality: 0
        aromaStatus: 0
        aromaTimeOff: 120
        aromaTimeOn: 90
        channel: appliance
        ecoModeStatus: 0
        humidityIndoor: 63.0
        lightStatus: 2
        lockStatus: 0
        machMode: 2
        mainFilterStatus: 59.0
        origin: dashboard
        pm10ValueIndoor: 9
        pm2p5ValueIndoor: 9
        pollenLevel: 1
        preFilterStatus: 53.0
        temp: 26
        touchToneStatus: 1
        vocValueIndoor: 1
        windSpeed: 2
      category: CYCLE
      macAddress: xx-xx-xx-xx-xx-xx
      resultCode: 0
      ttl: 1694281565
    lastConnEvent:
      category: CONNECTED
      instantTime: 2023-06-14T12:50:25Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1686747025855
    parameters:
      airQuality: 0
      aromaPreferredSetting: 1
      aromaStatus: 0
      aromaTimeOff: 120
      aromaTimeOn: 90
      coLevel: 0
      ecoModeStatus: 1
      errors: 00
      highTransRate: 5
      humidityIndoor: 62.0
      lightStatus: 2
      lockStatus: 0
      machMode: 2
      mainFilterStatus: 59.0
      onOffStatus: 1
      pm10ValueIndoor: 3
      pm2p5ValueIndoor: 3
      pollenLevel: 1
      preFilterStatus: 56.0
      stdTransRate: 3600
      temp: 26
      totalWorkTime: 145434
      touchToneStatus: 1
      transMode: 0
      vocValueIndoor: 1
      windSpeed: 1
    resultCode: 0
  settings:
    custom:
      category: setParameters
    parameters:
      aromaPreferredSetting: 1
      aromaStatus: 0
      aromaTimeOff: 60
      aromaTimeOn: 60
      highTransRate: 5
      lightStatus: 0
      lockStatus: 0
      machMode: 2
      mainFilterStatus: 0
      pollenLevel: 0
      preFilterStatus: 0
      stdTransRate: 3600
      touchToneStatus: 0
  startProgram:
    ancillaryParameters:
      remoteActionable: 1
      remoteVisible: 1
    custom:
      program: undefined
    parameters:
      aromaStatus: 0
      lightStatus: 0
      machMode: 2
      onOffStatus: 1
  statistics:
    mostUsedPrograms:
    mostUsedRecipes:
    programsCounter: 0
  stopProgram:
    parameters:
      onOffStatus: 0
commands:
  settings:
    aromaPreferredSetting:
      max: 4
      min: 1
      step: 1
    aromaStatus:
      max: 4
      min: 0
      step: 1
    aromaTimeOff:
      max: 86400
      min: 1
      step: 1
    aromaTimeOn:
      max: 86400
      min: 1
      step: 1
    category:
      - setConfig
      - setParameters
    highTransRate:
      max: 86400
      min: 1
      step: 1
    lightStatus:
      max: 2
      min: 0
      step: 1
    lockStatus:
      max: 1
      min: 0
      step: 1
    machMode:
      - 1
      - 2
      - 4
    pollenLevel:
      max: 2
      min: 0
      step: 1
    stdTransRate:
      max: 86400
      min: 1
      step: 1
    touchToneStatus:
      max: 1
      min: 0
      step: 1
  startProgram:
    aromaStatus:
      max: 4
      min: 0
      step: 1
    lightStatus:
      max: 2
      min: 0
      step: 1
    machMode:
      - 1
      - 2
      - 4
    program:
      - undefined
rules:
pyhOnVersion: 0.12.4
```
