### ISSUE TITLE
Oven's configs don't show in 0.9 beta

### ISSUE THREAD

**Issue by MiguelAngelLV** [Andre0512/hon#88]
**Describe the bug**
In the 0.9.X versions, oven has not config inputs.

Show the values but has not inputs.

**To Reproduce**
1. Update to 0.9 beta
2. Go to oven page

**Expected behavior**
Oven must have inputs to set temperature, program, preheat...

**Screenshots**

![image](https://github.com/Andre0512/hon/assets/638110/59f1455e-1ecd-462f-a6c4-4bf28dbd8da9)

**Environment (please complete the following information):**
 - Home Assistant Version: 2023.6.3
 - hOn Integration Version v0.9.0-beta.8

**Additional context**
I have only a Oven with Hon, I don't know if others devices have the same problem.

**Home Assistant Logs**
Check `System` -> `Logs` if you can find any logs related to this integration and post it here.

**Device Log**
```
data:
  additional_data:
    dictionaryId: 59
  appliance:
    PK: user#eu-west-1:2619534f-e0a8-4b1e-83e7-319a94de1506
    SK: app#xx-xx-xx-xx-xx-xx
    applianceId: xx-xx-xx-xx-xx-xx#1970-01-01T00:00:00.0Z
    applianceModelId: 577
    applianceStatus: 1
    applianceTypeId: 4
    applianceTypeName: OV
    attributes:
      acuVersion: 016P.P.000
      chipset: ESP32D0WDQ5
      dictionaryId: 59
      lang: it-IT
      uiVersion: 0.0.0
    brand: haier
    code: 33703247
    connectivity: wifi|ble
    eepromId: 235
    eepromName: 42837571
    enrollmentDate: 1970-01-01T00:00:00.0Z
    firstEnrollment: False
    firstEnrollmentTBC: False
    fwVersion: 5.1.0
    id: 577
    lastUpdate: 1970-01-01T00:00:00.0Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: HWO60SM2F3XH
    sections:
      chatbot: True
    series: series2
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
    zone: 1
  attributes:
    active: False
    activity:
    commandHistory:
      command:
        ancillaryParameters:
        applianceOptions:
        applianceType: OV
        attributes:
          channel: mobileApp
          energyLabel: 0
          origin: standardProgram
        commandName: stopProgram
        device:
          appVersion: 2.0.10
          deviceModel: exynos9820
          mobileId: 2901956acf6d6c34
          mobileOs: android
          osVersion: 31
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          onOffStatus: 0
          recipeId: NULL
          recipeStep: 0
        timestamp: 1970-01-01T00:00:00.0Z
        transactionId: xx-xx-xx-xx-xx-xx_1970-01-01T00:00:00.0Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 1970-01-01T00:00:00.0Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1688539451755
    parameters:
      clockHH: 9
      clockMM: 20
      clockSS: 8
      delayTime: 0
      errors: 00
      lockStatus: 0
      machMode: 1
      onOffStatus: 0
      prCode: 5
      prPosition: 1
      prTime: 240
      preheatStatus: 0
      programCount: 233
      programStats: 6F;45;;;4;3;4;6;7;19;4
      recipeCount: 6
      recipeId: NULL
      recipeStats: ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;6
      recipeStep: 0
      remainingTimeMM: 0
      remoteCtrValid: 1
      temp: 62
      tempSel: 50
      tempStatus: 0
    programName: conventional
    resultCode: 0
  settings:
    custom:
      category: setParameters
    parameters:
      clockHH: 9
      clockMM: 20
      clockSS: 8
      idEmployedProbe1: 0
      prTime: 240
      tempSel: 50
      tempSelEmployedProbe1: 30
  startProgram:
    ancillaryParameters:
      probe: 0
      programFamily: [guided|special]
      remoteActionable: 1
      remoteVisible: 0
    custom:
      program: iot_guided_yogurt
    parameters:
      delayTime: 0
      onOffStatus: 1
      prCode: 5
      prPosition: 1
      prTime: 240
      recipeId: 958
      recipeStep: 1
      tempSel: 50
  statistics:
    filterCleaning:
      count: 0
      percentage: 0
      remaining: 4
      tot: 4
    mostUsedPrograms:
    mostUsedRecipes:
    programsCounter: 0
  stopProgram:
    parameters:
      onOffStatus: 0
      recipeId: NULL
      recipeStep: 0
commands:
  settings:
    category:
      - setConfig
      - setParameters
    clockHH:
      max: 23
      min: 0
      step: 1
    clockMM:
      max: 59
      min: 0
      step: 1
    clockSS:
      max: 59
      min: 0
      step: 1
    prTime:
      max: 240
      min: 1
      step: 1
    tempSel:
      max: 280
      min: 50
      step: 5
    tempSelEmployedProbe1:
      max: 90
      min: 30
      step: 1
  startProgram:
    delayTime:
      max: 1439
      min: 0
      step: 1
    portion:
      max: 8
      min: 4
      step: 4
    prCode:
      - 5
      - 25
    prPosition:
      - 1
      - 25
    prTime:
      max: 240
      min: 0
      step: 1
    preheatStatus:
      max: 1
      min: 0
      step: 1
    probe:
      max: 1
      min: 0
      step: 1
    program:
      - bottom_heating
      - bottom_heating_fan
      - convection_fan
      - conventional
      - h20_clean
      - multi_level
      - soft_plus
      - tailor_bake_cata
    programFamily:
      - guided
      - special
      - guided_special
    recipeStep:
      - 1
      - 2
    tempSel:
      max: 280
      min: 50
      step: 5
    zoneEmployedProbe1:
      max: 3
      min: 0
      step: 3
versions:
  hon: 0.9.0-beta.8
  pyhOn: 0.12.4
```

**Data Archive**
[ov_577.zip](https://github.com/Andre0512/hon/files/11954972/ov_577.zip)
